CREATE TABLE IF NOT EXISTS records (
  kind TEXT NOT NULL,
  id TEXT NOT NULL,
  data TEXT NOT NULL,
  PRIMARY KEY (kind, id)
);
CREATE TABLE IF NOT EXISTS processed (id INTEGER PRIMARY KEY, at INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS lease (id INTEGER PRIMARY KEY CHECK (id = 1), owner TEXT NOT NULL, expires INTEGER NOT NULL);
CREATE TABLE IF NOT EXISTS commits (owner TEXT PRIMARY KEY);
CREATE TRIGGER IF NOT EXISTS require_lease BEFORE INSERT ON commits
WHEN NOT EXISTS (SELECT 1 FROM lease WHERE id = 1 AND owner = NEW.owner AND expires > unixepoch())
BEGIN SELECT RAISE(ABORT, 'lease lost'); END;
CREATE TABLE IF NOT EXISTS outbox (
  id TEXT PRIMARY KEY,
  method TEXT NOT NULL,
  params TEXT NOT NULL,
  due INTEGER NOT NULL DEFAULT 0,
  attempts INTEGER NOT NULL DEFAULT 0
);
