import { Miniflare, convertV4MiniflareOptions } from 'miniflare';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';

const telegramCalls=[];
const mf = new Miniflare(convertV4MiniflareOptions({
  workers: [{ name: 'test',
  modules: true, scriptPath: '.wrangler/build/worker.js', compatibilityDate: '2026-10-05', compatibilityFlags: ['nodejs_compat'],
  d1Databases: ['DB'], bindings: { SUPER_ADMIN_ID: '999001', BOT_USERNAME: 'XEvents_bot', APP_URL: 'https://test/app', TELEGRAM_BOT_TOKEN: 'fake', TELEGRAM_WEBHOOK_SECRET: 'test-secret' },
  outboundService: async request => {
    if(request.method==='POST' && request.headers.get('Content-Type')?.includes('application/json'))telegramCalls.push({method:new URL(request.url).pathname.split('/').at(-1),params:await request.clone().json()});
    if (request.url.includes('/file/bot')) return new Response(new Uint8Array([255,216,255]), { headers: { 'Content-Type':'image/jpeg' } });
    return new Response(JSON.stringify({ ok: true, result: request.url.endsWith('/sendPhoto') ? { photo:[{file_id:'test-banner'}] } : request.url.endsWith('/getFile') ? {file_path:'photos/banner.jpg'} : {} }), { headers: { 'Content-Type': 'application/json' } });
  }
  }]
}));
try {
  const db = await mf.getD1Database('DB');
  const schema = await readFile('migrations/0001_initial.sql', 'utf8');
  // Keep the trigger body together; D1 exec accepts one statement per line.
  await db.exec(schema.replace(/\n/g, ' '));
  await db.exec(await readFile('migrations/0002_delivery_lease.sql', 'utf8'));
  await db.exec(await readFile('migrations/0003_mini_app.sql', 'utf8'));
  assert.equal((await mf.dispatchFetch('https://test/')).status, 200);
  assert.equal((await mf.dispatchFetch('https://test/telegram', { method: 'POST', body: '{}' })).status, 401);
  async function message(update_id, text, uid = 123, extra = {}) {
    const body = { update_id, message: { from: { id: uid, first_name: 'Tester' }, chat: { id: uid, type: 'private' }, text, ...extra } };
    const response = await mf.dispatchFetch('https://test/telegram', { method: 'POST', headers: { 'X-Telegram-Bot-Api-Secret-Token': 'test-secret' }, body: JSON.stringify(body) });
    assert.equal(response.status, 200, await response.text());
  }
  async function callback(update_id, data, uid = 123) {
    const response = await mf.dispatchFetch('https://test/telegram', { method: 'POST', headers: { 'X-Telegram-Bot-Api-Secret-Token': 'test-secret' }, body: JSON.stringify({ update_id, callback_query: { id: String(update_id), from: { id: uid, first_name: 'Tester' }, data } }) });
    assert.equal(response.status, 200);
  }
  const texts = ['/new', 'Cloud event', 'Tomorrow 6pm Sydney', 'Park', '/skip', 'Dietary needs?'];
  for (const [i, text] of texts.entries()) await message(i + 1, text);
  const creationToken = JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='sessions' AND id='123'").first()).data).token;
  await callback(1001, `pd:${creationToken}`);
  const event = await db.prepare("SELECT data FROM records WHERE kind='events'").first();
  assert.equal(JSON.parse(event.data).title, 'Cloud event');
  await message(6, 'Dietary needs?');
  assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM records WHERE kind='events'").first()).n, 1);
  assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM processed').first()).n, 7);
  assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM lease').first()).n, 0);
  const initData = uid => {
    const params = new URLSearchParams({ auth_date: String(Math.floor(Date.now()/1000)), user: JSON.stringify({ id: uid, first_name: 'Tester' }), query_id: 'query' });
    const data = [...params.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([k,v]) => `${k}=${v}`).join('\n');
    const key = createHmac('sha256', 'WebAppData').update('fake').digest();
    params.set('hash', createHmac('sha256', key).update(data).digest('hex')); return params.toString();
  };
  async function api(path, input, uid = 123) {
    const response = await mf.dispatchFetch('https://test/api/' + path, { method: input ? 'POST' : 'GET', headers: { Authorization: 'tma ' + initData(uid), 'Content-Type': 'application/json' }, ...(input ? { body: JSON.stringify(input) } : {}) });
    return { status: response.status, data: await response.json() };
  }
  assert.equal((await mf.dispatchFetch('https://test/api/bootstrap')).status, 401);
  assert.equal((await api('admin/overview',null,123)).status,403);
  assert.equal((await api('bootstrap')).data.user.isSuperAdmin,false);
  assert.equal((await api('bootstrap',null,999001)).data.user.isSuperAdmin,true);
  assert.equal((await api('bootstrap')).data.events.length, 1);
  assert.equal((await api('bootstrap', null, 456)).data.events.length, 0);
  assert.equal((await api('preferences', { timezone: 'America/New_York' })).status, 200);
  const input = { askPhone:true,askComments:true,invitationMode:'legacy',title: 'Mini app event', location: 'Cafe', description: '', questions: 'Diet?', date: '2026-10-24', time: '18:00', timezone: 'Australia/Sydney', requestId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' };
  const made = await api('events', input); assert.equal(made.status, 200); assert.equal(made.data.event.startsAt, '2026-10-24T07:00:00Z');
  assert.equal((await api('events', input)).data.event.id, made.data.event.id);
  assert.equal((await api('bootstrap')).data.events.length, 2);
  assert.equal((await api('bootstrap')).data.preference.timezone, 'America/New_York');
  const path = `events/${made.data.event.id}/schedule`;
  assert.equal((await api(path, { ...input, time: '19:00' }, 456)).status, 400);
  assert.equal((await api(path, { ...input, time: '19:00' })).data.event.startsAt, '2026-10-24T08:00:00Z');
  assert.equal((await api('preview', { date: '2026-10-04', time: '02:30', timezone: 'Australia/Sydney' })).status, 400);
  await message(7, '/new'); await message(8, 'Picker event'); await message(9, '🗓 Pick date & time');
  const bootstrap = (await api('bootstrap')).data;
  assert.ok(bootstrap.session.token);
  assert.equal((await api('picker', { ...input, sessionToken: 'wrong' })).status, 400);
  assert.equal((await api('picker', { ...input, sessionToken: bootstrap.session.token })).status, 200);
  const session = JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='sessions' AND id='123'").first()).data);
  assert.equal(session.step, 'location'); assert.equal(session.draft.startsAt, '2026-10-24T07:00:00Z');
  assert.equal((await api('picker', { ...input, sessionToken: bootstrap.session.token })).status, 400);
  await message(10, 'Park'); await message(11, '/skip'); await message(12, '/skip');
  const deadlineSession = (await api('bootstrap')).data.session;
  assert.equal((await api('draft-deadline', { date: '2026-10-20', time: '12:00', timezone: 'Australia/Sydney', sessionToken: deadlineSession.token })).status, 200);
  await callback(1002, `pd:${deadlineSession.token}`);
  assert.equal((await api('bootstrap')).data.events.find(e => e.title === 'Picker event').startsAt, '2026-10-24T07:00:00Z');
  const privateInput = { ...input, requestId: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', title: 'Approval event', location: 'SECRET LOCATION', questions: '', requireApproval: true, hideLocation: true, ticketInfo: 'SECRET TICKET', deadlineDate: '2026-10-20', deadlineTime: '12:00', permissions: { guestList: false, uploadMedia: false, viewMedia: false } };
  const privateMade = await api('events', privateInput); assert.equal(privateMade.status, 200);
  const privateId = privateMade.data.event.id;
  assert.equal((await api('events', { ...privateInput, requestId: 'cccccccc-cccc-cccc-cccc-cccccccccccc', deadlineDate: '2026-10-25' })).status, 400);
  await message(20, `/start e_${privateId}`, 456);
  let guestView = (await api('bootstrap', null, 456)).data.events[0];
  assert.equal(guestView.location, null); assert.equal(guestView.counts, null); assert.equal(guestView.ticket, null);
  assert.doesNotMatch(JSON.stringify(guestView), /SECRET/);
  await callback(21, `r:${privateId}:yes`, 456);
  await message(22, 'Guest', 456); await message(23, '/skip', 456); await message(24, '/skip', 456);
  guestView = (await api('bootstrap', null, 456)).data.events[0]; assert.equal(guestView.approval, 'pending'); assert.equal(guestView.location, null);
  await callback(25, `approve:${privateId}:456`, 456); assert.equal((await api('bootstrap', null, 456)).data.events[0].approval, 'pending');
  await db.prepare("UPDATE records SET data=json_set(data,'$.responseDeadline','2020-01-01T00:00:00Z') WHERE kind='events' AND id=?").bind(privateId).run();
  await callback(26, `r:${privateId}:no`, 456); assert.equal((await api('bootstrap', null, 456)).data.events[0].status, 'yes');
  await callback(27, `approve:${privateId}:456`);
  guestView = (await api('bootstrap', null, 456)).data.events[0]; assert.equal(guestView.approval, 'approved'); assert.equal(guestView.location, 'SECRET LOCATION'); assert.equal(guestView.ticket.info, 'SECRET TICKET'); assert.ok(guestView.ticket.code);
  assert.equal((await api('bootstrap')).data.events.find(e => e.id === privateId).counts.yes, 1);
  assert.equal((await api('bootstrap', null, 789)).data.events.length, 0);
  assert.equal((await api(`events/${privateId}/reminder`, {minutes:60},456)).status,200);
  assert.equal((await api('bootstrap',null,456)).data.events[0].reminder,60);
  assert.equal((await api(`events/${privateId}/reminder`, {minutes:60},789)).status,400);
  assert.equal((await api(`events/${privateId}/reminder`, {minutes:0},456)).status,200);
  const form=new FormData(); form.set('photo',new File([new Uint8Array([255,216,255])],'banner.jpg',{type:'image/jpeg'}));
  const uploadRequest=new Request('https://test/upload',{method:'POST',body:form});
  const uploadBytes=await uploadRequest.arrayBuffer(); const uploadType=uploadRequest.headers.get('Content-Type');
  assert.equal((await mf.dispatchFetch(`https://test/api/events/${privateId}/banner`,{method:'POST',headers:{Authorization:'tma '+initData(456),'Content-Type':uploadType},body:uploadBytes})).status,403);
  const uploaded=await mf.dispatchFetch(`https://test/api/events/${privateId}/banner`,{method:'POST',headers:{Authorization:'tma '+initData(123),'Content-Type':uploadType},body:uploadBytes});
  assert.equal(uploaded.status,200); assert.equal((await uploaded.json()).event.hasBanner,true);
  assert.equal((await mf.dispatchFetch(`https://test/api/events/${privateId}/banner`,{headers:{Authorization:'tma '+initData(789)}})).status,403);
  const image=await mf.dispatchFetch(`https://test/api/events/${privateId}/banner`,{headers:{Authorization:'tma '+initData(456)}});
  assert.equal(image.status,200); assert.equal(image.headers.get('Content-Type'),'image/jpeg'); assert.equal((await image.arrayBuffer()).byteLength,3);
  const overview=await api('admin/overview',null,999001);
  assert.equal(overview.status,200);
  assert.equal(overview.data.events.length,(await api('bootstrap')).data.events.length);
  assert.equal(overview.data.events.find(e=>e.id===privateId).location,'SECRET LOCATION');
  assert.equal(overview.data.events.find(e=>e.id===privateId).guests[0].id,456);
  assert.ok(overview.data.users.some(u=>u.id===123 && u.organised.includes(privateId)));
  assert.ok(overview.data.users.some(u=>u.id===456 && u.invited.includes(privateId)));
  assert.ok(overview.data.users.some(u=>u.id===999001 && u.firstName==='Tester'));
  assert.doesNotMatch(JSON.stringify(overview.data),/sessionToken|test-secret|test-banner|query_id/);
  assert.equal((await api('admin/overview',null,456)).status,403);
  assert.equal((await api('admin/overview',{id:999001},456)).status,403);
  const disposable=await api('events',{...input,requestId:'dddddddd-dddd-dddd-dddd-dddddddddddd',defaultReminder:240});
  const disposableId=disposable.data.event.id; assert.equal(disposable.data.event.defaultReminder,240);
  assert.equal((await api(`events/${disposableId}/cancel`,{confirm:true},456)).status,400);
  assert.equal((await api(`events/${disposableId}/delete`,{confirm:false})).status,400);
  assert.equal((await api(`events/${disposableId}/cancel`,{confirm:true})).status,200);
  assert.equal((await api('bootstrap')).data.events.find(e=>e.id===disposableId).cancelled,true);
  assert.equal((await api(`events/${disposableId}/delete`,{confirm:true})).status,200);
  assert.ok(!(await api('bootstrap')).data.events.some(e=>e.id===disposableId));
  const durationMade=await api('events',{...input,requestId:'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',endMode:'duration',durationMinutes:180});
  assert.equal(durationMade.data.event.endsAt,'2026-10-24T10:00:00Z');
  const durationPath=`events/${durationMade.data.event.id}/schedule`;
  const changed=await api(durationPath,{...input,time:'19:00'}); assert.equal(changed.data.event.endsAt,'2026-10-24T11:00:00Z');
  assert.equal((await api(durationPath,{...input,endMode:'finish',endDate:'2026-10-24',endTime:'17:00'})).status,400);
  const finished=await api(durationPath,{...input,endMode:'finish',endDate:'2026-10-25',endTime:'01:00'});
  assert.equal(finished.data.event.endsAt,'2026-10-24T14:00:00Z');
  assert.equal((await api(durationPath,{...input,endMode:'none'})).data.event.endsAt,null);
  const galleryMade=await api('events',{...input,requestId:'ffffffff-ffff-ffff-ffff-ffffffffffff',allowLinkUploads:true,permissions:{uploadMedia:true,viewMedia:true}});
  const galleryId=galleryMade.data.event.id;
  assert.match(galleryMade.data.event.uploadLink,/https:\/\/t.me\/XEvents_bot\?start=u_[a-f0-9]{32}/);
  const qr=await api(`events/${galleryId}/upload-qr`);assert.equal(qr.status,200);assert.match(qr.data.image,/^data:image\/gif;base64,/);assert.equal(qr.data.link,galleryMade.data.event.uploadLink);
  assert.equal((await api(`events/${galleryId}/gallery`,null,789)).status,403);
  await message(2000,'/start '+new URL(qr.data.link).searchParams.get('start'),789);
  await callback(2010,`media-add:${galleryId}`,789);
  await message(2001,undefined,789,{photo:[{file_id:'public-image',file_size:3}]});
  const storedGallery=JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(galleryId).first()).data);
  assert.equal(storedGallery.media.length,1);assert.equal(storedGallery.guests[789],undefined);
  assert.equal((await api(`events/${galleryId}/gallery`,null,789)).status,200);
  assert.equal((await api('preferences',{timezone:'UTC'},789)).status,200);
  assert.equal((await api(`events/${galleryId}/gallery`,null,789)).status,200);
  assert.doesNotMatch(JSON.stringify((await api('bootstrap',null,789)).data.preference),/mediaAccess/);
  await message(2002,`/start e_${galleryId}`,456);
  const gallery=await api(`events/${galleryId}/gallery`,null,456);assert.equal(gallery.status,200);assert.equal(gallery.data.media.length,1);assert.doesNotMatch(JSON.stringify(gallery.data),/public-image|uploadToken/);
  const mediaId=gallery.data.media[0].id;
  const file=await mf.dispatchFetch(`https://test/api/events/${galleryId}/media/${mediaId}`,{headers:{Authorization:'tma '+initData(456)}});assert.equal(file.status,200);
  assert.equal((await api(`events/${galleryId}/media/${mediaId}/send`,{},456)).status,200);
  assert.equal((await api(`events/${galleryId}/upload-qr`,null,456)).status,403);
  await callback(2003,`toggle:${galleryId}:viewMedia`);
  assert.equal((await api(`events/${galleryId}/gallery`,null,456)).status,403);
  await callback(2004,`toggle:${galleryId}:allowLinkUploads`);
  assert.equal((await api(`events/${galleryId}/gallery`,null,789)).status,403);
  await message(2005,undefined,789,{photo:[{file_id:'disabled-image'}]});
  assert.equal(JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(galleryId).first()).data).media.length,1);
  const publicInput={...input,date:'2099-10-24',title:'Explore Sydney',isPublic:true,location:'EXPLORE PRIVATE LOCATION',requireApproval:true,ticketInfo:'EXPLORE PRIVATE TICKET',requestId:'11111111-1111-1111-1111-111111111111'};
  const publicEvent=await api('events',publicInput);assert.equal(publicEvent.status,200);assert.equal(publicEvent.data.event.isPublic,true);
  const publicId=publicEvent.data.event.id;
  const privateEvent=await api('events',{...publicInput,title:'PRIVATE TITLE',isPublic:false,requestId:'22222222-2222-2222-2222-222222222222'});assert.equal(privateEvent.status,200);
  const otherZone=await api('events',{...publicInput,timezone:'Europe/London',title:'Explore London',requestId:'33333333-3333-3333-3333-333333333333'});assert.equal(otherZone.status,200);
  const explore=await api('explore?timezone=Australia%2FSydney',null,789);assert.equal(explore.status,200);assert.ok(explore.data.events.some(e=>e.id===publicId));
  assert.doesNotMatch(JSON.stringify(explore.data),/PRIVATE TITLE|EXPLORE PRIVATE|Explore London|ticketInfo|uploadToken|guests/);
  assert.equal((await api('explore?timezone=Invalid')).status,400);
  await api(`events/${publicId}/schedule`,{...publicInput,isPublic:false});assert.ok(!(await api('explore?timezone=Australia%2FSydney')).data.events.some(e=>e.id===publicId));
  await api(`events/${publicId}/schedule`,{...publicInput,isPublic:true});await api(`events/${publicId}/cancel`,{confirm:true});assert.ok(!(await api('explore?timezone=Australia%2FSydney')).data.events.some(e=>e.id===publicId));
  const groupEvent = await api('events', {...input, date:'2099-10-24', askParticipantCount:true, requireApproval:false, requestId:'44444444-4444-4444-4444-444444444444'});
  assert.equal(groupEvent.status,200); assert.equal(groupEvent.data.event.askParticipantCount,true);
  const groupId=groupEvent.data.event.id;
  assert.equal((await api(`events/${groupId}/schedule`, {...input, date:'2099-10-24', askParticipantCount:'yes'})).status,400);
  await message(3000,`/start e_${groupId}`,456); await callback(3001,`r:${groupId}:yes`,456);
  await message(3002,'Group guest',456); await message(3003,'4',456);
  for (let i=0;i<4;i++) await message(3004+i,'/skip',456);
  const groupStored=JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(groupId).first()).data);
  assert.equal(groupStored.guests[456].participants,4); assert.equal(groupStored.guests[456].status,'yes');
  const hostGroup=(await api('bootstrap')).data.events.find(e=>e.id===groupId);
  assert.equal(hostGroup.counts.yes,1); assert.equal(hostGroup.counts.participants,4);
  assert.equal((await api('bootstrap',null,456)).data.events.find(e=>e.id===groupId).participants,4);
  const disabledGroup=await api(`events/${groupId}/schedule`, {...input,date:'2099-10-24',askParticipantCount:false});
  assert.equal(disabledGroup.status,200); assert.equal(disabledGroup.data.event.counts.participants,1);
  const ownerPricing={defaultStarPrice:50,defaultStarPricing:'person'};
  assert.equal((await api('admin/pricing',ownerPricing,123)).status,403);
  assert.equal((await api('admin/pricing',{...ownerPricing,defaultStarPrice:-1},999001)).status,400);
  assert.equal((await api('admin/pricing',ownerPricing,999001)).status,200);
  assert.equal((await api('admin/overview',null,999001)).data.pricing.defaultStarPrice,50);
  await db.prepare("INSERT INTO app_settings(key,value) VALUES ('online-currency-rates',?)").bind(JSON.stringify({rates:{AUD:0.0195},dates:{AUD:'2026-10-05'},retrievedAt:new Date().toISOString(),basis:'organiser-reward'})).run();
  const pricedBootstrap=(await api('bootstrap')).data;
  assert.equal(pricedBootstrap.pricing.rates.AUD,0.0195);
  assert.equal(pricedBootstrap.pricing.basis,'organiser-reward');
  await api('preferences',{timezone:'Australia/Sydney',currency:''},456);
  assert.equal((await api('bootstrap',null,456)).data.localCurrency,'AUD');
  await api('preferences',{timezone:'Asia/Dubai',currency:'AED'},456);
  assert.equal((await api('bootstrap',null,456)).data.localCurrency,'AED');
  assert.equal((await api('preferences',{timezone:'UTC',currency:'INVALID'},456)).status,400);
  const starsInput={...input,date:'2099-10-24',starPrice:20,starPricing:'person',paymentTerms:'Online workshop. Full refund on cancellation. Contact the organiser for other requests.',askParticipantCount:true,requireApproval:true,requestId:'55555555-5555-5555-5555-555555555555'};
  assert.equal((await api('events',starsInput,123)).status,200);
  assert.equal((await api('events',{...starsInput,starPrice:1.5},999001)).status,400);
  const starsEvent=await api('events',starsInput,999001);assert.equal(starsEvent.status,200);
  const starsId=starsEvent.data.event.id;
  await message(4000,`/start e_${starsId}`,456);await callback(4001,`r:${starsId}:yes`,456);
  await message(4002,'Stars guest',456);await message(4003,'2',456);for(let i=0;i<4;i++)await message(4004+i,'/skip',456);
  await callback(4010,`approve:${starsId}:456`,999001);
  await callback(4011,`star-pay:${starsId}`,456);
  const pref=JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='preferences' AND id='456'").first()).data);
  const starOrder=Object.values(pref.starOrders).find(o=>o.event===starsId);assert.equal(starOrder.amount,40);
  const checkoutUpdate={update_id:4012,pre_checkout_query:{id:'stars-checkout',from:{id:456},invoice_payload:starOrder.id,currency:'XTR',total_amount:40}};
  const checkoutRequest=()=>mf.dispatchFetch('https://test/telegram',{method:'POST',headers:{'X-Telegram-Bot-Api-Secret-Token':'test-secret'},body:JSON.stringify(checkoutUpdate)});
  assert.equal((await checkoutRequest()).status,200);assert.equal((await checkoutRequest()).status,200);
  assert.ok(telegramCalls.some(c=>c.method==='answerPreCheckoutQuery' && c.params.ok===true));
  assert.equal((await api('bootstrap',null,456)).data.events.find(e=>e.id===starsId).ticket,null);
  const payment={currency:'XTR',total_amount:40,invoice_payload:starOrder.id,telegram_payment_charge_id:'integration-charge'};
  await message(4013,undefined,456,{successful_payment:payment});await message(4013,undefined,456,{successful_payment:payment});
  const paidEvent=(await api('bootstrap',null,456)).data.events.find(e=>e.id===starsId);
  assert.equal(paidEvent.paymentStatus,'paid');assert.ok(paidEvent.ticket);assert.equal(paidEvent.location,input.location);
  assert.doesNotMatch(JSON.stringify((await api('bootstrap',null,456)).data),/integration-charge|starOrders|checkoutId/);
  assert.equal((await api(`events/${starsId}/schedule`,{...starsInput,starPrice:30},999001)).status,400);
  await api(`events/${starsId}/delete`,{confirm:true},999001);
  const durablePref=JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='preferences' AND id='456'").first()).data);
  assert.ok(['refund_pending','refunded'].includes(durablePref.starOrders[starOrder.id].status));
  assert.equal((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(starsId).first()),null);
  const ticketInput={...input,title:'Ticket workflow',questions:'',date:'2099-10-24',requestId:'66666666-6666-6666-6666-666666666666',requireApproval:true};delete ticketInput.invitationMode;
  const ticketEvent=await api('events',ticketInput);assert.equal(ticketEvent.status,200);assert.equal(ticketEvent.data.event.invitationMode,'tickets');
  const ticketId=ticketEvent.data.event.id;
  await message(5000,`/start e_${ticketId}`,456);await callback(5001,`book:${ticketId}`,456);await message(5002,'Ticket Guest',456);await message(5003,'/skip',456);await message(5004,'/skip',456);
  assert.equal((await api(`events/${ticketId}`,null,456)).data.event.approval,'pending');
  assert.equal((await api(`events/${ticketId}/ticket`,{},456)).status,400);
  await callback(5005,`approve:${ticketId}:456`);
  const qrTicket=await api(`events/${ticketId}/ticket`,{},456);assert.equal(qrTicket.status,200);assert.match(qrTicket.data.ticket.image,/^data:image\/gif;base64,/);
  const ticketCode=qrTicket.data.ticket.code;
  assert.equal((await api(`events/${ticketId}/ticket-check`,{code:ticketCode},456)).status,400);
  const checkinMessages=()=>telegramCalls.filter(c=>c.method==='sendMessage' && c.params.chat_id===456 && c.params.text?.startsWith('✅ Checked in\n'+ticketInput.title));
  const validated=await api(`events/${ticketId}/ticket-check`,{code:`XE1:${ticketId}:${ticketCode}`});assert.equal(validated.data.ticket.valid,true);assert.equal(validated.data.ticket.checkedInAt,null);
  assert.equal(checkinMessages().length,0);
  const admitted=await api(`events/${ticketId}/ticket-check`,{code:ticketCode,checkIn:true});assert.equal(admitted.data.ticket.valid,true);assert.equal(admitted.data.ticket.alreadyCheckedIn,false);
  // The notification commits with attendance; background delivery may still be draining older messages.
  const queuedCheckins=async()=> (await db.prepare("SELECT params FROM outbox WHERE method='sendMessage' AND json_extract(params,'$.chat_id')=456 AND json_extract(params,'$.text')=?").bind('✅ Checked in\n'+ticketInput.title+'\n1 person').all()).results;
  const queued=await queuedCheckins();assert.ok(checkinMessages().length===1 || queued.length===1);
  assert.match((checkinMessages()[0]?.params || JSON.parse(queued[0].params)).text,/1 person$/);
  const repeated=await api(`events/${ticketId}/ticket-check`,{code:ticketCode,checkIn:true});assert.equal(repeated.data.ticket.alreadyCheckedIn,true);assert.equal(repeated.data.ticket.checkedInAt,admitted.data.ticket.checkedInAt);
  const stillQueued=await queuedCheckins();assert.ok(stillQueued.length<=1);assert.ok(checkinMessages().length<=1);
  assert.ok(checkinMessages().length===1 || stillQueued.length===1);
  const checkedEvent=JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(ticketId).first()).data);assert.equal(checkedEvent.checkIns[ticketCode].userId,456);
  await api(`events/${ticketId}/cancel`,{confirm:true});assert.equal((await api(`events/${ticketId}/ticket-check`,{code:ticketCode})).data.ticket.valid,false);
  const namedInput={...ticketInput,title:'Named workflow',invitationMode:'named',guestNames:'Alex Smith\nSam Jones',requestId:'77777777-7777-7777-7777-777777777777'};
  const namedEvent=await api('events',namedInput);assert.equal(namedEvent.status,200);assert.equal(namedEvent.data.event.invitees.length,2);
  const namedId=namedEvent.data.event.id,personalUrl=namedEvent.data.event.invitees[0].url;
  await message(5010,'/start '+new URL(personalUrl).searchParams.get('start'),456);
  await message(5011,'/start '+new URL(personalUrl).searchParams.get('start'),789);
  assert.equal((await api(`events/${namedId}`,null,789)).status,403);
  const personalView=(await api(`events/${namedId}`,null,456)).data.event;assert.equal(personalView.guestName,'Alex Smith');assert.equal(personalView.invitees,undefined);
  await callback(5012,`r:${namedId}:yes`,456);
  assert.equal(JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='sessions' AND id='456'").first()).data).step,'phone');
  await message(5013,'/skip',456);await message(5014,'/skip',456);
  const editedNamed=await api(`events/${namedId}/schedule`,{...namedInput,title:'Edited title',location:'Edited address',description:'Edited description',questions:'New question?',guestNames:'Alex Smith\nSam Jones\nTaylor'});
  assert.equal(editedNamed.status,200);assert.equal(editedNamed.data.event.invitees[0].url,personalUrl);
  const freshNamed=(await api(`events/${namedId}`)).data.event;
  assert.equal(freshNamed.title,'Edited title');assert.equal(freshNamed.location,'Edited address');assert.deepEqual(freshNamed.questions,['New question?']);
  assert.equal((await api(`events/${namedId}/schedule`,{...namedInput,invitationMode:'tickets'})).status,400);
  assert.equal((await api(`events/${namedId}/schedule`,{...namedInput,guestNames:'Sam Jones'})).status,400);
  console.log('Worker integration passed: ticket bookings, personal RSVP links, owner-only edit loading, approvals, Stars checkout, durable refunds and media. Telegram mocked.');
} finally { await mf.dispose(); }
