import { Miniflare, convertV4MiniflareOptions } from 'miniflare';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
import { createHmac } from 'node:crypto';

const telegramCalls=[];
const mf = new Miniflare(convertV4MiniflareOptions({
  workers: [{ name: 'test',
  modules: true, scriptPath: '.wrangler/build/worker.js', compatibilityDate: '2026-10-05', compatibilityFlags: ['nodejs_compat'],
  d1Databases: ['DB'], bindings: { SUPER_ADMIN_ID: '999001', BOT_USERNAME: 'XEvents_bot', APP_URL: 'https://test/app', TELEGRAM_BOT_TOKEN: 'fake', TELEGRAM_WEBHOOK_SECRET: 'test-secret' },
  serviceBindings: { ASSETS: async request => {
    const pathname=new URL(request.url).pathname;
    const file=pathname==='/' ? 'index.html' : pathname.slice(1);
    if(!['index.html','app.js','errors.js','gallery.js','event-actions.js','style.css'].includes(file))return new Response('Not found',{status:404});
    return new Response(await readFile('public/'+file),{headers:{'Content-Type':file.endsWith('.js') ? 'application/javascript' : file.endsWith('.css') ? 'text/css' : 'text/html'}});
  } },
  outboundService: async request => {
    if(request.method==='POST' && request.headers.get('Content-Type')?.includes('application/json'))telegramCalls.push({method:new URL(request.url).pathname.split('/').at(-1),params:await request.clone().json()});
    if (request.url.includes('/file/bot')) return new Response(new Uint8Array([255,216,255]), { headers: { 'Content-Type':'image/jpeg' } });
    return new Response(JSON.stringify({ ok: true, result: request.url.endsWith('/sendPhoto') ? { photo:[{file_id:'test-banner'}] } : request.url.endsWith('/getFile') ? {file_path:'photos/banner.jpg'} : {} }), { headers: { 'Content-Type': 'application/json' } });
  }
  }]
}));
try {
  const db = await mf.getD1Database('DB');
  const schema = await readFile('migrations/0001_initial.sql', 'utf8');
  // Keep the trigger body together; D1 exec accepts one statement per line.
  await db.exec(schema.replace(/\n/g, ' '));
  await db.exec(await readFile('migrations/0002_delivery_lease.sql', 'utf8'));
  await db.exec(await readFile('migrations/0003_mini_app.sql', 'utf8'));
  assert.equal((await mf.dispatchFetch('https://test/')).status, 200);
  const appPage=await mf.dispatchFetch('https://test/app');
  assert.equal(appPage.status,200);assert.match(await appPage.text(),/id="event-end-dialog"/);
  const appModule=await mf.dispatchFetch('https://test/app.js');
  assert.equal(appModule.status,200);
  const imports=[...(await appModule.text()).matchAll(/import\s+.*?from\s+['"]\.\/([^'"]+)['"]/g)].map(match=>match[1]);
  assert.ok(imports.includes('event-actions.js'));
  for(const file of imports){
    const asset=await mf.dispatchFetch('https://test/'+file);
    assert.equal(asset.status,200,file+' must be served by the Worker');
    assert.match(asset.headers.get('Content-Type'),/javascript/);
    assert.equal(asset.headers.get('Cache-Control'),'no-cache');
    assert.equal(await asset.text(),await readFile('public/'+file,'utf8'));
  }
  assert.equal((await mf.dispatchFetch('https://test/telegram', { method: 'POST', body: '{}' })).status, 401);
  async function telegramUpdate(body){
    for(let attempt=0;attempt<12;attempt++){
      const response=await mf.dispatchFetch('https://test/telegram',{method:'POST',headers:{'X-Telegram-Bot-Api-Secret-Token':'test-secret'},body:JSON.stringify(body)});
      const text=await response.text();
      // Telegram redelivers the same update when concurrent writes encounter the D1 lease.
      if(response.status===503 && attempt<11){await new Promise(resolve=>setTimeout(resolve,Math.min(25*(attempt+1),200)));continue;}
      assert.equal(response.status,200,text);return;
    }
  }
  async function message(update_id, text, uid = 123, extra = {}) {
    await telegramUpdate({ update_id, message: { from: { id: uid, first_name: 'Tester' }, chat: { id: uid, type: 'private' }, text, ...extra } });
  }
  async function callback(update_id, data, uid = 123) {
    await telegramUpdate({ update_id, callback_query: { id: String(update_id), from: { id: uid, first_name: 'Tester' }, data } });
  }
  const texts = ['/new', 'Cloud event', 'Tomorrow 6pm Sydney', 'Park', '/skip', 'Dietary needs?'];
  for (const [i, text] of texts.entries()) await message(i + 1, text);
  const creationToken = JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='sessions' AND id='123'").first()).data).token;
  await callback(1001, `pd:${creationToken}`);
  const event = await db.prepare("SELECT data FROM records WHERE kind='events'").first();
  assert.equal(JSON.parse(event.data).title, 'Cloud event');
  await message(6, 'Dietary needs?');
  assert.equal((await db.prepare("SELECT COUNT(*) AS n FROM records WHERE kind='events'").first()).n, 1);
  assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM processed').first()).n, 7);
  assert.equal((await db.prepare('SELECT COUNT(*) AS n FROM lease').first()).n, 0);
  const initData = uid => {
    const params = new URLSearchParams({ auth_date: String(Math.floor(Date.now()/1000)), user: JSON.stringify({ id: uid, first_name: 'Tester' }), query_id: 'query' });
    const data = [...params.entries()].sort(([a], [b]) => a.localeCompare(b)).map(([k,v]) => `${k}=${v}`).join('\n');
    const key = createHmac('sha256', 'WebAppData').update('fake').digest();
    params.set('hash', createHmac('sha256', key).update(data).digest('hex')); return params.toString();
  };
  async function api(path, input, uid = 123) {
    const response = await mf.dispatchFetch('https://test/api/' + path, { method: input ? 'POST' : 'GET', headers: { Authorization: 'tma ' + initData(uid), 'Content-Type': 'application/json' }, ...(input ? { body: JSON.stringify(input) } : {}) });
    return { status: response.status, data: await response.json() };
  }
  assert.equal((await mf.dispatchFetch('https://test/api/bootstrap')).status, 401);
  assert.equal((await api('admin/overview',null,123)).status,403);
  assert.equal((await api('bootstrap')).data.user.isSuperAdmin,false);
  assert.equal((await api('bootstrap',null,999001)).data.user.isSuperAdmin,true);
  assert.equal((await api('bootstrap')).data.events.length, 1);
  assert.equal((await api('bootstrap', null, 456)).data.events.length, 0);
  assert.equal((await api('preferences', { timezone: 'America/New_York' })).status, 200);
  const input = { askPhone:true,askComments:true,invitationMode:'legacy',title: 'Mini app event', location: 'Cafe', description: '', questions: 'Diet?', date: '2026-10-24', time: '18:00', timezone: 'Australia/Sydney', requestId: 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa' };
  const made = await api('events', input); assert.equal(made.status, 200); assert.equal(made.data.event.startsAt, '2026-10-24T07:00:00Z');
  assert.equal(made.data.event.qrEnabled,false);assert.equal(made.data.event.questions,undefined);
  assert.equal((await api('events', input)).data.event.id, made.data.event.id);
  assert.equal((await api('bootstrap')).data.events.length, 2);
  assert.equal((await api('bootstrap')).data.preference.timezone, 'America/New_York');
  const path = `events/${made.data.event.id}/schedule`;
  assert.equal((await api(path, { ...input, time: '19:00' }, 456)).status, 400);
  assert.equal((await api(path, { ...input, time: '19:00' })).data.event.startsAt, '2026-10-24T08:00:00Z');
  assert.equal((await api('preview', { date: '2026-10-04', time: '02:30', timezone: 'Australia/Sydney' })).status, 400);
  await message(7, '/new'); await message(8, 'Picker event'); await message(9, '🗓 Pick date & time');
  const bootstrap = (await api('bootstrap')).data;
  assert.ok(bootstrap.session.token);
  assert.equal((await api('picker', { ...input, sessionToken: 'wrong' })).status, 400);
  assert.equal((await api('picker', { ...input, sessionToken: bootstrap.session.token })).status, 200);
  const session = JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='sessions' AND id='123'").first()).data);
  assert.equal(session.step, 'location'); assert.equal(session.draft.startsAt, '2026-10-24T07:00:00Z');
  assert.equal((await api('picker', { ...input, sessionToken: bootstrap.session.token })).status, 400);
  await message(10, 'Park'); await message(11, '/skip'); await message(12, '/skip');
  const deadlineSession = (await api('bootstrap')).data.session;
  assert.equal((await api('draft-deadline', { date: '2026-10-20', time: '12:00', timezone: 'Australia/Sydney', sessionToken: deadlineSession.token })).status, 200);
  await callback(1002, `pd:${deadlineSession.token}`);
  assert.equal((await api('bootstrap')).data.events.find(e => e.title === 'Picker event').startsAt, '2026-10-24T07:00:00Z');
  const privateInput = { ...input, requestId: 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', title: 'Approval event', location: 'SECRET LOCATION', questions: '', requireApproval: true, hideLocation: true, ticketInfo: 'SECRET TICKET', deadlineDate: '2026-10-20', deadlineTime: '12:00', permissions: { guestList: false, uploadMedia: false, viewMedia: false } };
  const privateMade = await api('events', privateInput); assert.equal(privateMade.status, 200);
  const privateId = privateMade.data.event.id;
  assert.equal((await api('events', { ...privateInput, requestId: 'cccccccc-cccc-cccc-cccc-cccccccccccc', deadlineDate: '2026-10-25' })).status, 400);
  await message(20, `/start e_${privateId}`, 456);
  let guestView = (await api('bootstrap', null, 456)).data.events[0];
  assert.equal(guestView.location, null); assert.equal(guestView.counts, null); assert.equal(guestView.ticket, null);
  assert.doesNotMatch(JSON.stringify(guestView), /SECRET/);
  await callback(21, `r:${privateId}:yes`, 456);
  await message(22, 'Guest', 456); await message(23, '/skip', 456); await message(24, '/skip', 456);
  guestView = (await api('bootstrap', null, 456)).data.events[0]; assert.equal(guestView.approval, 'pending'); assert.equal(guestView.location, null);
  await callback(25, `approve:${privateId}:456`, 456); assert.equal((await api('bootstrap', null, 456)).data.events[0].approval, 'pending');
  await db.prepare("UPDATE records SET data=json_set(data,'$.responseDeadline','2020-01-01T00:00:00Z') WHERE kind='events' AND id=?").bind(privateId).run();
  await callback(26, `r:${privateId}:no`, 456); assert.equal((await api('bootstrap', null, 456)).data.events[0].status, 'yes');
  await callback(27, `approve:${privateId}:456`);
  guestView = (await api('bootstrap', null, 456)).data.events[0]; assert.equal(guestView.approval, 'approved'); assert.equal(guestView.location, 'SECRET LOCATION'); assert.equal(guestView.ticket.info, 'SECRET TICKET'); assert.ok(guestView.ticket.code);
  assert.equal((await api('bootstrap')).data.events.find(e => e.id === privateId).counts.yes, 1);
  assert.equal((await api('bootstrap', null, 789)).data.events.length, 0);
  assert.equal((await api(`events/${privateId}/reminder`, {minutes:60},456)).status,200);
  assert.equal((await api('bootstrap',null,456)).data.events[0].reminder,60);
  assert.equal((await api(`events/${privateId}/reminder`, {minutes:60},789)).status,400);
  assert.equal((await api(`events/${privateId}/reminder`, {minutes:0},456)).status,200);
  const form=new FormData(); form.set('photo',new File([new Uint8Array([255,216,255])],'banner.jpg',{type:'image/jpeg'}));
  const uploadRequest=new Request('https://test/upload',{method:'POST',body:form});
  const uploadBytes=await uploadRequest.arrayBuffer(); const uploadType=uploadRequest.headers.get('Content-Type');
  assert.equal((await mf.dispatchFetch(`https://test/api/events/${privateId}/banner`,{method:'POST',headers:{Authorization:'tma '+initData(456),'Content-Type':uploadType},body:uploadBytes})).status,403);
  const uploaded=await mf.dispatchFetch(`https://test/api/events/${privateId}/banner`,{method:'POST',headers:{Authorization:'tma '+initData(123),'Content-Type':uploadType},body:uploadBytes});
  assert.equal(uploaded.status,200); assert.equal((await uploaded.json()).event.hasBanner,true);
  assert.equal((await mf.dispatchFetch(`https://test/api/events/${privateId}/banner`,{headers:{Authorization:'tma '+initData(789)}})).status,403);
  const image=await mf.dispatchFetch(`https://test/api/events/${privateId}/banner`,{headers:{Authorization:'tma '+initData(456)}});
  assert.equal(image.status,200); assert.equal(image.headers.get('Content-Type'),'image/jpeg'); assert.equal((await image.arrayBuffer()).byteLength,3);
  const overview=await api('admin/overview',null,999001);
  assert.equal(overview.status,200);
  assert.equal(overview.data.events.length,(await api('bootstrap')).data.events.length);
  assert.equal(overview.data.events.find(e=>e.id===privateId).location,'SECRET LOCATION');
  assert.equal(overview.data.events.find(e=>e.id===privateId).guests[0].id,456);
  assert.ok(overview.data.users.some(u=>u.id===123 && u.organised.includes(privateId)));
  assert.ok(overview.data.users.some(u=>u.id===456 && u.invited.includes(privateId)));
  assert.ok(overview.data.users.some(u=>u.id===999001 && u.firstName==='Tester'));
  assert.doesNotMatch(JSON.stringify(overview.data),/sessionToken|test-secret|test-banner|query_id/);
  assert.equal((await api('admin/overview',null,456)).status,403);
  assert.equal((await api('admin/overview',{id:999001},456)).status,403);
  const disposable=await api('events',{...input,requestId:'dddddddd-dddd-dddd-dddd-dddddddddddd',defaultReminder:240});
  const disposableId=disposable.data.event.id; assert.equal(disposable.data.event.defaultReminder,240);
  assert.equal((await api(`events/${disposableId}/cancel`,{confirm:true},456)).status,400);
  assert.equal((await api(`events/${disposableId}/delete`,{confirm:false})).status,400);
  assert.equal((await api(`events/${disposableId}/cancel`,{confirm:true})).status,200);
  assert.equal((await api('bootstrap')).data.events.find(e=>e.id===disposableId).cancelled,true);
  assert.equal((await api(`events/${disposableId}/delete`,{confirm:true})).status,200);
  assert.ok(!(await api('bootstrap')).data.events.some(e=>e.id===disposableId));
  const durationMade=await api('events',{...input,requestId:'eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee',endMode:'duration',durationMinutes:180});
  assert.equal(durationMade.data.event.endsAt,'2026-10-24T10:00:00Z');
  const durationPath=`events/${durationMade.data.event.id}/schedule`;
  const changed=await api(durationPath,{...input,time:'19:00'}); assert.equal(changed.data.event.endsAt,'2026-10-24T11:00:00Z');
  assert.equal((await api(durationPath,{...input,endMode:'finish',endDate:'2026-10-24',endTime:'17:00'})).status,400);
  const finished=await api(durationPath,{...input,endMode:'finish',endDate:'2026-10-25',endTime:'01:00'});
  assert.equal(finished.data.event.endsAt,'2026-10-24T14:00:00Z');
  assert.equal((await api(durationPath,{...input,endMode:'none'})).data.event.endsAt,null);
  const galleryMade=await api('events',{...input,qrEnabled:true,requestId:'ffffffff-ffff-ffff-ffff-ffffffffffff',allowLinkUploads:true,permissions:{uploadMedia:true,viewMedia:true}});
  const galleryId=galleryMade.data.event.id;
  assert.match(galleryMade.data.event.uploadLink,/https:\/\/t.me\/XEvents_bot\?start=u_[a-f0-9]{32}/);
  const qr=await api(`events/${galleryId}/upload-qr`);assert.equal(qr.status,200);assert.match(qr.data.image,/^data:image\/gif;base64,/);assert.equal(qr.data.link,galleryMade.data.event.uploadLink);
  assert.equal((await api(`events/${galleryId}/gallery`,null,789)).status,403);
  await message(2000,'/start '+new URL(qr.data.link).searchParams.get('start'),789);
  await callback(2010,`media-add:${galleryId}`,789);
  await message(2001,undefined,789,{photo:[{file_id:'public-image',file_size:3}]});
  const storedGallery=JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(galleryId).first()).data);
  assert.equal(storedGallery.media.length,1);assert.equal(storedGallery.guests[789],undefined);
  assert.equal((await api(`events/${galleryId}/gallery`,null,789)).status,200);
  assert.equal((await api('preferences',{timezone:'UTC'},789)).status,200);
  assert.equal((await api(`events/${galleryId}/gallery`,null,789)).status,200);
  assert.doesNotMatch(JSON.stringify((await api('bootstrap',null,789)).data.preference),/mediaAccess/);
  await message(2002,`/start e_${galleryId}`,456);
  const gallery=await api(`events/${galleryId}/gallery`,null,456);assert.equal(gallery.status,200);assert.equal(gallery.data.media.length,1);assert.doesNotMatch(JSON.stringify(gallery.data),/public-image|uploadToken/);
  const mediaId=gallery.data.media[0].id;
  const file=await mf.dispatchFetch(`https://test/api/events/${galleryId}/media/${mediaId}`,{headers:{Authorization:'tma '+initData(456)}});assert.equal(file.status,200);
  assert.equal((await api(`events/${galleryId}/media/${mediaId}/send`,{},456)).status,200);
  assert.equal((await api(`events/${galleryId}/upload-qr`,null,456)).status,403);
  await callback(2003,`toggle:${galleryId}:viewMedia`);
  assert.equal((await api(`events/${galleryId}/gallery`,null,456)).status,403);
  await callback(2004,`toggle:${galleryId}:allowLinkUploads`);
  assert.equal((await api(`events/${galleryId}/gallery`,null,789)).status,403);
  await message(2005,undefined,789,{photo:[{file_id:'disabled-image'}]});
  assert.equal(JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(galleryId).first()).data).media.length,1);
  const publicInput={...input,date:'2099-10-24',title:'Explore Sydney',isPublic:true,location:'EXPLORE PRIVATE LOCATION',requireApproval:true,ticketInfo:'EXPLORE PRIVATE TICKET',requestId:'11111111-1111-1111-1111-111111111111'};
  const publicEvent=await api('events',publicInput);assert.equal(publicEvent.status,200);assert.equal(publicEvent.data.event.isPublic,true);
  const publicId=publicEvent.data.event.id;
  const privateEvent=await api('events',{...publicInput,title:'PRIVATE TITLE',isPublic:false,requestId:'22222222-2222-2222-2222-222222222222'});assert.equal(privateEvent.status,200);
  const otherZone=await api('events',{...publicInput,timezone:'Europe/London',title:'Explore London',requestId:'33333333-3333-3333-3333-333333333333'});assert.equal(otherZone.status,200);
  const explore=await api('explore?timezone=Australia%2FSydney',null,789);assert.equal(explore.status,200);assert.ok(explore.data.events.some(e=>e.id===publicId));
  assert.doesNotMatch(JSON.stringify(explore.data),/PRIVATE TITLE|EXPLORE PRIVATE|Explore London|ticketInfo|uploadToken|guests/);
  assert.equal((await api('explore?timezone=Invalid')).status,400);
  await api(`events/${publicId}/schedule`,{...publicInput,isPublic:false});assert.ok(!(await api('explore?timezone=Australia%2FSydney')).data.events.some(e=>e.id===publicId));
  await api(`events/${publicId}/schedule`,{...publicInput,isPublic:true});await api(`events/${publicId}/cancel`,{confirm:true});assert.ok(!(await api('explore?timezone=Australia%2FSydney')).data.events.some(e=>e.id===publicId));
  const groupEvent = await api('events', {...input, date:'2099-10-24', askParticipantCount:true, requireApproval:false, requestId:'44444444-4444-4444-4444-444444444444'});
  assert.equal(groupEvent.status,200); assert.equal(groupEvent.data.event.askParticipantCount,true);
  const groupId=groupEvent.data.event.id;
  assert.equal((await api(`events/${groupId}/schedule`, {...input, date:'2099-10-24', askParticipantCount:'yes'})).status,400);
  await message(3000,`/start e_${groupId}`,456); await callback(3001,`r:${groupId}:yes`,456);
  await message(3002,'Group guest',456); await message(3003,'4',456);
  for (let i=0;i<4;i++) await message(3004+i,'/skip',456);
  const groupStored=JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(groupId).first()).data);
  assert.equal(groupStored.guests[456].participants,4); assert.equal(groupStored.guests[456].status,'yes');
  const hostGroup=(await api('bootstrap')).data.events.find(e=>e.id===groupId);
  assert.equal(hostGroup.counts.yes,1); assert.equal(hostGroup.counts.participants,4);
  assert.equal((await api('bootstrap',null,456)).data.events.find(e=>e.id===groupId).participants,4);
  const disabledGroup=await api(`events/${groupId}/schedule`, {...input,date:'2099-10-24',askParticipantCount:false});
  assert.equal(disabledGroup.status,200); assert.equal(disabledGroup.data.event.counts.participants,1);
  const ownerPricing={defaultStarPrice:50,defaultStarPricing:'person'};
  assert.equal((await api('admin/pricing',ownerPricing,123)).status,403);
  assert.equal((await api('admin/pricing',{...ownerPricing,defaultStarPrice:-1},999001)).status,400);
  assert.equal((await api('admin/pricing',ownerPricing,999001)).status,200);
  assert.equal((await api('admin/overview',null,999001)).data.pricing.defaultStarPrice,50);
  await db.prepare("INSERT INTO app_settings(key,value) VALUES ('online-currency-rates',?)").bind(JSON.stringify({rates:{AUD:0.0195},dates:{AUD:'2026-10-05'},retrievedAt:new Date().toISOString(),basis:'organiser-reward'})).run();
  const pricedBootstrap=(await api('bootstrap')).data;
  assert.equal(pricedBootstrap.pricing.rates.AUD,0.0195);
  assert.equal(pricedBootstrap.pricing.basis,'organiser-reward');
  await api('preferences',{timezone:'Australia/Sydney',currency:''},456);
  assert.equal((await api('bootstrap',null,456)).data.localCurrency,'AUD');
  await api('preferences',{timezone:'Asia/Dubai',currency:'AED'},456);
  assert.equal((await api('bootstrap',null,456)).data.localCurrency,'AED');
  assert.equal((await api('preferences',{timezone:'UTC',currency:'INVALID'},456)).status,400);
  const starsInput={...input,date:'2099-10-24',starPrice:20,starPricing:'person',paymentTerms:'Online workshop. Full refund on cancellation. Contact the organiser for other requests.',askParticipantCount:true,requireApproval:true,requestId:'55555555-5555-5555-5555-555555555555'};
  assert.equal((await api('events',starsInput,123)).status,200);
  assert.equal((await api('events',{...starsInput,starPrice:1.5},999001)).status,400);
  const starsEvent=await api('events',starsInput,999001);assert.equal(starsEvent.status,200);
  const starsId=starsEvent.data.event.id;
  await message(4000,`/start e_${starsId}`,456);await callback(4001,`r:${starsId}:yes`,456);
  await message(4002,'Stars guest',456);await message(4003,'2',456);for(let i=0;i<4;i++)await message(4004+i,'/skip',456);
  await callback(4010,`approve:${starsId}:456`,999001);
  await callback(4011,`star-pay:${starsId}`,456);
  const pref=JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='preferences' AND id='456'").first()).data);
  const starOrder=Object.values(pref.starOrders).find(o=>o.event===starsId);assert.equal(starOrder.amount,40);
  const checkoutUpdate={update_id:4012,pre_checkout_query:{id:'stars-checkout',from:{id:456},invoice_payload:starOrder.id,currency:'XTR',total_amount:40}};
  const checkoutRequest=()=>mf.dispatchFetch('https://test/telegram',{method:'POST',headers:{'X-Telegram-Bot-Api-Secret-Token':'test-secret'},body:JSON.stringify(checkoutUpdate)});
  assert.equal((await checkoutRequest()).status,200);assert.equal((await checkoutRequest()).status,200);
  assert.ok(telegramCalls.some(c=>c.method==='answerPreCheckoutQuery' && c.params.ok===true));
  assert.equal((await api('bootstrap',null,456)).data.events.find(e=>e.id===starsId).ticket,null);
  const payment={currency:'XTR',total_amount:40,invoice_payload:starOrder.id,telegram_payment_charge_id:'integration-charge'};
  await message(4013,undefined,456,{successful_payment:payment});await message(4013,undefined,456,{successful_payment:payment});
  const paidEvent=(await api('bootstrap',null,456)).data.events.find(e=>e.id===starsId);
  assert.equal(paidEvent.paymentStatus,'paid');assert.ok(paidEvent.ticket);assert.equal(paidEvent.location,input.location);
  assert.doesNotMatch(JSON.stringify((await api('bootstrap',null,456)).data),/integration-charge|starOrders|checkoutId/);
  assert.equal((await api(`events/${starsId}/schedule`,{...starsInput,starPrice:30},999001)).status,400);
  await api(`events/${starsId}/delete`,{confirm:true},999001);
  const durablePref=JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='preferences' AND id='456'").first()).data);
  assert.ok(['refund_pending','refunded'].includes(durablePref.starOrders[starOrder.id].status));
  assert.equal((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(starsId).first()),null);
  const ticketInput={...input,qrEnabled:true,title:'Ticket workflow',date:'2099-10-24',requestId:'66666666-6666-6666-6666-666666666666',requireApproval:true};delete ticketInput.invitationMode;
  const ticketEvent=await api('events',ticketInput);assert.equal(ticketEvent.status,200);assert.equal(ticketEvent.data.event.invitationMode,'tickets');assert.equal(ticketEvent.data.event.oneTimeInvite,false);
  const ticketId=ticketEvent.data.event.id;
  await message(5000,`/start e_${ticketId}`,456);await callback(5001,`book:${ticketId}`,456);await message(5002,'Ticket Guest',456);await message(5003,'/skip',456);await message(5004,'/skip',456);
  assert.equal((await api(`events/${ticketId}`,null,456)).data.event.approval,'pending');
  assert.equal((await api(`events/${ticketId}/ticket`,{},456)).status,400);
  await callback(5005,`approve:${ticketId}:456`);
  const qrTicket=await api(`events/${ticketId}/ticket`,{},456);assert.equal(qrTicket.status,200);assert.match(qrTicket.data.ticket.image,/^data:image\/gif;base64,/);
  const ticketCode=qrTicket.data.ticket.code;
  assert.equal((await api(`events/${ticketId}/ticket-check`,{code:ticketCode},456)).status,400);
  const checkinMessages=()=>telegramCalls.filter(c=>c.method==='sendMessage' && c.params.chat_id===456 && c.params.text?.startsWith('✅ Checked in\n'+ticketInput.title));
  const validated=await api(`events/${ticketId}/ticket-check`,{code:`XE1:${ticketId}:${ticketCode}`});assert.equal(validated.data.ticket.valid,true);assert.equal(validated.data.ticket.checkedInAt,null);
  assert.equal(checkinMessages().length,0);
  const admitted=await api(`events/${ticketId}/ticket-check`,{code:ticketCode,checkIn:true});assert.equal(admitted.data.ticket.valid,true);assert.equal(admitted.data.ticket.alreadyCheckedIn,false);
  // The notification commits with attendance; background delivery may still be draining older messages.
  const queuedCheckins=async()=> (await db.prepare("SELECT params FROM outbox WHERE method='sendMessage' AND json_extract(params,'$.chat_id')=456 AND json_extract(params,'$.text')=?").bind('✅ Checked in\n'+ticketInput.title+'\n1 person').all()).results;
  const queued=await queuedCheckins();assert.ok(checkinMessages().length===1 || queued.length===1);
  assert.match((checkinMessages()[0]?.params || JSON.parse(queued[0].params)).text,/1 person$/);
  const repeated=await api(`events/${ticketId}/ticket-check`,{code:ticketCode,checkIn:true});assert.equal(repeated.data.ticket.alreadyCheckedIn,true);assert.equal(repeated.data.ticket.checkedInAt,admitted.data.ticket.checkedInAt);
  const stillQueued=await queuedCheckins();assert.ok(stillQueued.length<=1);assert.ok(checkinMessages().length<=1);
  assert.ok(checkinMessages().length===1 || stillQueued.length===1);
  const checkedEvent=JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(ticketId).first()).data);assert.equal(checkedEvent.checkIns[ticketCode].userId,456);
  await api(`events/${ticketId}/cancel`,{confirm:true});assert.equal((await api(`events/${ticketId}/ticket-check`,{code:ticketCode})).data.ticket.valid,false);
  const namedInput={...ticketInput,title:'Named workflow',invitationMode:'named',askParticipantCount:true,inviteMessage:'Join our club celebration!',guestNames:'Alex Smith = 3\nSam Jones',requestId:'77777777-7777-7777-7777-777777777777'};
  const namedEvent=await api('events',namedInput);assert.equal(namedEvent.status,200);assert.equal(namedEvent.data.event.invitees.length,2);assert.equal(namedEvent.data.event.oneTimeInvite,true);assert.equal(namedEvent.data.event.requireApproval,false);assert.equal(namedEvent.data.event.askParticipantCount,false);
  const namedId=namedEvent.data.event.id,personalUrl=namedEvent.data.event.invitees[0].url;
  await message(5010,'/start '+new URL(personalUrl).searchParams.get('start'),456);
  await message(5011,'/start '+new URL(personalUrl).searchParams.get('start'),789);
  assert.equal((await api(`events/${namedId}`,null,789)).status,200);
  const personalView=(await api(`events/${namedId}`,null,456)).data.event;assert.equal(personalView.guestName,'Alex Smith');assert.equal(personalView.invitees,undefined);
  await callback(5012,`r:${namedId}:yes`,456);
  assert.equal(JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='sessions' AND id='456'").first()).data).step,'phone');
  await message(5013,'/skip',456);await message(5014,'/skip',456);
  const acceptedNamed=(await api(`events/${namedId}`,null,456)).data.event;assert.equal(acceptedNamed.participants,3);assert.equal(acceptedNamed.approval,'approved');
  assert.equal((await api(`events/${namedId}`,null,789)).status,403);
  const editedNamed=await api(`events/${namedId}/schedule`,{...namedInput,title:'Edited title',location:'Edited address',description:'Edited description',inviteMessage:'Updated welcome message',guestNames:'Alex Smith = 3\nSam Jones\nTaylor'});
  assert.equal(editedNamed.status,200);assert.equal(editedNamed.data.event.invitees[0].url,personalUrl);
  const freshNamed=(await api(`events/${namedId}`)).data.event;
  assert.equal(freshNamed.title,'Edited title');assert.equal(freshNamed.location,'Edited address');assert.equal(freshNamed.inviteMessage,'Updated welcome message');assert.equal(freshNamed.questions,undefined);assert.equal(freshNamed.invitees[0].participants,3);
  assert.equal((await api(`events/${namedId}/schedule`,{...namedInput,guestNames:'Alex Smith = 4\nSam Jones'})).status,400);
  assert.equal((await api(`events/${namedId}/schedule`,{...namedInput,qrEnabled:'no'})).status,400);
  assert.equal((await api(`events/${namedId}/schedule`,{...namedInput,inviteMessage:'X'.repeat(1001)})).status,400);
  assert.equal((await api(`events/${namedId}/schedule`,{...namedInput,invitationMode:'tickets'})).status,400);
  assert.equal((await api(`events/${namedId}/schedule`,{...namedInput,guestNames:'Sam Jones'})).status,400);
  // A named invitation can suggest, confirm or explicitly ask for group size.
  const countInput={...ticketInput,title:'Named attendee choices',invitationMode:'named',qrEnabled:false,askParticipantCount:false,askPhone:false,askComments:false,guestNames:'Default Guest = 3\nConfirm Guest = 4!\nChoose Guest = ?\nChange Guest = 2!',requestId:'88888888-8888-8888-8888-888888888888'};
  const countCreated=await api('events',countInput);assert.equal(countCreated.status,200);
  const countId=countCreated.data.event.id;
  const countRecord=async()=>JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(countId).first()).data);
  const countSession=async uid=>{const row=await db.prepare("SELECT data FROM records WHERE kind='sessions' AND id=?").bind(String(uid)).first();return row ? JSON.parse(row.data):null;};
  let countUpdate=7000;
  const openCountInvite=async (guestName,uid)=>{const link=countCreated.data.event.invitees.find(g=>g.name===guestName).url;await message(countUpdate++,'/start '+new URL(link).searchParams.get('start'),uid);};
  await openCountInvite('Default Guest',801);
  await callback(countUpdate++,`group:${countId}:edit:0`,801);
  let countState=await countSession(801);assert.equal(countState.step,'participants');
  await callback(countUpdate++,`size:${countId}:2:${countState.countToken}`,801);
  let countGuest=(await countRecord()).guests[801];assert.equal(countGuest.status,'later');assert.equal(countGuest.participants,2);
  await openCountInvite('Default Guest',801);
  assert.equal((await countRecord()).guests[801].participants,2);
  await callback(countUpdate++,`r:${countId}:yes:${countGuest.responseVersion}`,801);
  countGuest=(await countRecord()).guests[801];assert.equal(countGuest.status,'yes');assert.equal(countGuest.participants,2);assert.equal(countGuest.approval,'approved');assert.equal(await countSession(801),null);
  const approvedCountGuest=(await countRecord()).guests[801],oldCountTicket=approvedCountGuest.ticket;
  assert.ok(oldCountTicket);assert.equal(approvedCountGuest.approval,'approved');
  await callback(countUpdate++,`group:${countId}:edit:${approvedCountGuest.responseVersion}`,801);
  countState=await countSession(801);
  await callback(countUpdate++,`size:${countId}:3:${countState.countToken}`,801);
  countGuest=(await countRecord()).guests[801];assert.equal(countGuest.participants,3);assert.equal(countGuest.approval,'approved');assert.ok(countGuest.ticket);assert.notEqual(countGuest.ticket,oldCountTicket);assert.ok(countGuest.responseVersion>approvedCountGuest.responseVersion);
  assert.equal((await api(`events/${countId}/ticket-check`,{code:oldCountTicket})).data.ticket.valid,false);
  await openCountInvite('Default Guest',801);assert.equal((await countRecord()).guests[801].participants,3);
  await openCountInvite('Confirm Guest',802);
  await callback(countUpdate++,`r:${countId}:yes:0`,802);
  countState=await countSession(802);assert.equal(countState.step,'participantConfirm');assert.equal((await countRecord()).guests[802].status,'later');
  await callback(countUpdate++,`count-confirm:${countId}:yes:${countState.countToken}`,802);
  countGuest=(await countRecord()).guests[802];assert.equal(countGuest.status,'yes');assert.equal(countGuest.participants,4);assert.equal(countGuest.approval,'approved');assert.equal(await countSession(802),null);
  await openCountInvite('Change Guest',804);
  await callback(countUpdate++,`r:${countId}:yes:0`,804);
  countState=await countSession(804);assert.equal(countState.step,'participantConfirm');
  await callback(countUpdate++,`count-confirm:${countId}:change:${countState.countToken}`,804);
  countState=await countSession(804);assert.equal(countState.step,'participants');
  await callback(countUpdate++,`size:${countId}:5:${countState.countToken}`,804);
  assert.equal((await countRecord()).guests[804].participants,5);assert.equal(await countSession(804),null);
  await openCountInvite('Choose Guest',803);
  await callback(countUpdate++,`r:${countId}:yes:0`,803);
  countState=await countSession(803);assert.equal(countState.step,'participants');
  await callback(countUpdate++,`size:${countId}:10:${countState.countToken}`,803);
  countGuest=(await countRecord()).guests[803];assert.equal(countGuest.status,'yes');assert.equal(countGuest.participants,10);assert.equal(await countSession(803),null);
  assert.equal((await api(`events/${countId}`)).data.event.counts.pendingParticipants,0);assert.equal((await api(`events/${countId}`)).data.event.counts.participants,22);
  // One-time personal links lock only after the first final RSVP, including Reject and Maybe.
  const oneTimeInput={...ticketInput,title:'One-time personal invitations',invitationMode:'named',askPhone:false,askComments:false,askParticipantCount:true,requireApproval:true,guestNames:'Accept Guest\nReject Guest\nMaybe Guest\nRace Guest\nDelayed Guest = ?',requestId:'dededede-dede-dede-dede-dededededede'};
  const oneTimeCreated=await api('events',oneTimeInput);assert.equal(oneTimeCreated.status,200);
  const oneTimeId=oneTimeCreated.data.event.id;
  assert.equal(oneTimeCreated.data.event.oneTimeInvite,true);assert.equal(oneTimeCreated.data.event.requireApproval,false);assert.equal(oneTimeCreated.data.event.askParticipantCount,false);
  const inviteRecord=async id=>JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(id).first()).data);
  let inviteUpdate=10000;
  const inviteToken=guestName=>new URL(oneTimeCreated.data.event.invitees.find(guest=>guest.name===guestName).url).searchParams.get('start');
  const openOneTime=async(guestName,uid)=>message(inviteUpdate++,'/start '+inviteToken(guestName),uid);
  const respondOneTime=async(uid,status)=>{const guest=(await inviteRecord(oneTimeId)).guests[uid];await callback(inviteUpdate++,`r:${oneTimeId}:${status}:${guest?.responseVersion || 0}`,uid);};
  await Promise.all([openOneTime('Accept Guest',1101),openOneTime('Accept Guest',1102)]);
  assert.equal((await api(`events/${oneTimeId}`,null,1101)).status,200);assert.equal((await api(`events/${oneTimeId}`,null,1102)).status,200);
  await respondOneTime(1101,'later');
  let oneTimeStored=await inviteRecord(oneTimeId),acceptToken=inviteToken('Accept Guest').split('_').at(-1);
  assert.ok(!oneTimeStored.invitees[acceptToken].claimedBy);assert.ok(!oneTimeStored.invitees[acceptToken].respondedBy);
  await respondOneTime(1102,'yes');
  oneTimeStored=await inviteRecord(oneTimeId);
  assert.equal(oneTimeStored.invitees[acceptToken].claimedBy,1102);assert.equal(oneTimeStored.invitees[acceptToken].respondedBy,1102);
  assert.equal(oneTimeStored.guests[1102].status,'yes');assert.equal(oneTimeStored.guests[1102].approval,'approved');assert.equal(oneTimeStored.guests[1101],undefined);
  assert.equal((await api(`events/${oneTimeId}`,null,1101)).status,403);
  await respondOneTime(1101,'yes');assert.equal((await inviteRecord(oneTimeId)).guests[1101],undefined);
  await openOneTime('Accept Guest',1101);assert.equal((await api(`events/${oneTimeId}`,null,1101)).status,403);
  // Older stored invitations had claimedBy only; revising a final RSVP to Later must preserve that lock.
  const olderBinding=await inviteRecord(oneTimeId);delete olderBinding.invitees[acceptToken].respondedBy;
  await db.prepare("UPDATE records SET data=? WHERE kind='events' AND id=?").bind(JSON.stringify(olderBinding),oneTimeId).run();
  await respondOneTime(1102,'later');assert.equal((await inviteRecord(oneTimeId)).invitees[acceptToken].respondedBy,1102);
  await openOneTime('Accept Guest',1101);assert.equal((await api(`events/${oneTimeId}`,null,1101)).status,403);
  // The holder can revise their RSVP; choosing Later afterwards never releases a consumed link.
  await openOneTime('Accept Guest',1102);await respondOneTime(1102,'maybe');await respondOneTime(1102,'later');
  assert.equal((await inviteRecord(oneTimeId)).invitees[acceptToken].respondedBy,1102);
  await openOneTime('Accept Guest',1101);assert.equal((await api(`events/${oneTimeId}`,null,1101)).status,403);
  await respondOneTime(1102,'no');assert.equal((await inviteRecord(oneTimeId)).guests[1102].status,'no');
  for(const [guestName,status,holder,forwarded] of [['Reject Guest','no',1111,1112],['Maybe Guest','maybe',1121,1122]]){
    await openOneTime(guestName,holder);await respondOneTime(holder,status);await openOneTime(guestName,forwarded);
    const stored=await inviteRecord(oneTimeId),token=inviteToken(guestName).split('_').at(-1);
    assert.equal(stored.invitees[token].respondedBy,holder);assert.equal(stored.guests[holder].status,status);assert.equal(stored.guests[forwarded],undefined);
    assert.equal((await api(`events/${oneTimeId}`,null,forwarded)).status,403);
  }
  // Two already-opened copies racing to accept can produce only one final response.
  await Promise.all([openOneTime('Race Guest',1131),openOneTime('Race Guest',1132)]);
  await Promise.all([respondOneTime(1131,'yes'),respondOneTime(1132,'yes')]);
  oneTimeStored=await inviteRecord(oneTimeId);
  const raceToken=inviteToken('Race Guest').split('_').at(-1),raceHolder=oneTimeStored.invitees[raceToken].respondedBy;
  assert.ok([1131,1132].includes(raceHolder));assert.equal(oneTimeStored.guests[raceHolder].status,'yes');assert.equal(oneTimeStored.guests[raceHolder===1131?1132:1131],undefined);
  assert.equal(Object.values(oneTimeStored.guests).filter(guest=>guest.invitationToken===raceToken && ['yes','no','maybe'].includes(guest.status)).length,1);
  // A final response from another account invalidates a count picker that was already open.
  await openOneTime('Delayed Guest',1141);await openOneTime('Delayed Guest',1142);await respondOneTime(1141,'yes');
  const delayedSession=await countSession(1141);assert.equal(delayedSession.step,'participants');
  await respondOneTime(1142,'no');await callback(inviteUpdate++,`size:${oneTimeId}:4:${delayedSession.countToken}`,1141);
  oneTimeStored=await inviteRecord(oneTimeId);assert.equal(oneTimeStored.guests[1141],undefined);assert.equal(oneTimeStored.guests[1142].status,'no');assert.equal(await countSession(1141),null);
  // The setting is editable before responses; disabling it allows multiple accounts to reuse a link.
  const reusableInput={...oneTimeInput,title:'Reusable personal link',guestNames:'Reusable Guest',oneTimeInvite:false,requestId:'acacacac-acac-acac-acac-acacacacacac'};
  const reusableCreated=await api('events',reusableInput);assert.equal(reusableCreated.status,200);assert.equal(reusableCreated.data.event.oneTimeInvite,false);
  const reusableId=reusableCreated.data.event.id;
  assert.equal((await api(`events/${reusableId}/schedule`,{...reusableInput,oneTimeInvite:true})).data.event.oneTimeInvite,true);
  assert.equal((await api(`events/${reusableId}/schedule`,{...reusableInput,oneTimeInvite:false})).data.event.oneTimeInvite,false);
  const reusableStart=new URL(reusableCreated.data.event.invitees[0].url).searchParams.get('start');
  for(const uid of [1151,1152]){await message(inviteUpdate++,'/start '+reusableStart,uid);await callback(inviteUpdate++,`r:${reusableId}:yes:0`,uid);assert.equal((await api(`events/${reusableId}`,null,uid)).status,200);}
  assert.equal((await api(`events/${reusableId}`)).data.event.counts.yes,2);
  assert.equal((await api(`events/${reusableId}/schedule`,{...reusableInput,oneTimeInvite:true})).status,400);
  assert.equal((await api(`events/${reusableId}`)).data.event.oneTimeInvite,false);
  assert.equal((await api(`events/${reusableId}/schedule`,{...reusableInput,oneTimeInvite:'yes'})).status,400);
  assert.equal((await api('events',{...reusableInput,oneTimeInvite:'yes',requestId:'bcbcbcbc-bcbc-bcbc-bcbc-bcbcbcbcbcbc'})).status,400);
  // A one-time general ticket link also stays open through name entry and closes on final booking.
  const singleTicketInput={...ticketInput,title:'One-time ticket link',oneTimeInvite:true,requireApproval:false,askPhone:false,askComments:false,requestId:'cdcdcdcd-cdcd-cdcd-cdcd-cdcdcdcdcdcd'};
  const singleTicketCreated=await api('events',singleTicketInput);assert.equal(singleTicketCreated.status,200);assert.equal(singleTicketCreated.data.event.oneTimeInvite,true);
  const singleTicketId=singleTicketCreated.data.event.id;
  for(const uid of [1161,1162]){await message(inviteUpdate++,`/start e_${singleTicketId}`,uid);await callback(inviteUpdate++,`book:${singleTicketId}`,uid);assert.equal((await countSession(uid)).step,'name');}
  assert.ok(!(await inviteRecord(singleTicketId)).inviteClaimedBy);
  await message(inviteUpdate++,'First ticket holder',1161);await message(inviteUpdate++,'Stale ticket holder',1162);
  const singleTicketStored=await inviteRecord(singleTicketId);assert.equal(singleTicketStored.inviteClaimedBy,1161);assert.equal(singleTicketStored.guests[1161].status,'yes');assert.equal(singleTicketStored.guests[1162],undefined);assert.equal(await countSession(1162),null);
  await message(inviteUpdate++,`/start e_${singleTicketId}`,1162);assert.equal((await api(`events/${singleTicketId}`,null,1162)).status,403);
  const profileSaved=await api('preferences',{timezone:'Australia/Sydney',profileName:'Profile name',profilePhone:'+61 400 123 456'});assert.equal(profileSaved.status,200);
  assert.equal((await api('bootstrap')).data.preference.profileName,'Profile name');assert.equal((await api('bootstrap',null,789)).data.preference.profilePhone,'');
  assert.equal((await api('preferences',{timezone:'UTC',profilePhone:'invalid'})).status,400);
  assert.equal((await api('bootstrap')).data.preference.timezone,'Australia/Sydney');
  const photoForm=new FormData();photoForm.set('photo',new File([new Uint8Array([255,216,255])],'profile.jpg',{type:'image/jpeg'}));
  const photoRequest=new Request('https://test/upload',{method:'POST',body:photoForm}),photoBytes=await photoRequest.arrayBuffer();
  assert.equal((await mf.dispatchFetch('https://test/api/profile/photo',{method:'POST',headers:{Authorization:'tma '+initData(123),'Content-Type':photoRequest.headers.get('Content-Type')},body:photoBytes})).status,200);
  assert.equal((await api('bootstrap')).data.preference.hasPhoto,true);assert.equal((await api('bootstrap')).data.preference.profilePhoto,undefined);
  assert.equal((await mf.dispatchFetch('https://test/api/profile/photo',{headers:{Authorization:'tma '+initData(123)}})).status,200);
  assert.equal((await mf.dispatchFetch('https://test/api/profile/photo',{headers:{Authorization:'tma '+initData(789)}})).status,404);
  assert.equal((await mf.dispatchFetch('https://test/api/profile/photo',{method:'DELETE',headers:{Authorization:'tma '+initData(123)}})).status,200);
  const iconUpload=uid=>mf.dispatchFetch('https://test/api/branding/icon',{method:'POST',headers:{Authorization:'tma '+initData(uid),'Content-Type':photoRequest.headers.get('Content-Type')},body:photoBytes});
  assert.equal((await iconUpload(123)).status,403);
  assert.equal((await iconUpload(999001)).status,200);
  assert.equal((await api('bootstrap')).data.branding.hasIcon,true);
  assert.equal((await mf.dispatchFetch('https://test/api/branding/icon',{headers:{Authorization:'tma '+initData(789)}})).status,200);
  assert.equal((await mf.dispatchFetch('https://test/api/branding/icon',{method:'DELETE',headers:{Authorization:'tma '+initData(123)}})).status,403);
  assert.equal((await mf.dispatchFetch('https://test/api/branding/icon',{method:'DELETE',headers:{Authorization:'tma '+initData(999001)}})).status,200);
  assert.equal((await api('bootstrap')).data.branding.hasIcon,false);
  assert.equal((await api('bootstrap')).data.preference.hasPhoto,false);
  await callback(6000,`u:${galleryId}`);
  await message(6001,undefined,123,{document:{file_id:'image-document',file_name:'photo.png',mime_type:'image/png',file_size:4,thumbnail:{file_id:'image-thumb'}}});
  await message(6002,undefined,123,{video:{file_id:'video-file',file_size:30000000,thumbnail:{file_id:'video-thumb'}}});
  const previewGallery=(await api(`events/${galleryId}/gallery`)).data.media;
  const documentPreview=previewGallery.find(f=>f.filename==='photo.png'),videoPreview=previewGallery.find(f=>f.type==='video');
  assert.equal(documentPreview.previewKind,'photo');assert.equal(videoPreview.previewKind,'video');assert.equal(videoPreview.hasThumbnail,true);
  assert.doesNotMatch(JSON.stringify(previewGallery),/image-thumb|video-thumb|image-document/);
  assert.equal((await mf.dispatchFetch(`https://test/api/events/${galleryId}/media/${documentPreview.id}`,{headers:{Authorization:'tma '+initData(123)}})).headers.get('Content-Type'),'image/png');
  assert.equal((await mf.dispatchFetch(`https://test/api/events/${galleryId}/media/${videoPreview.id}/thumbnail`,{headers:{Authorization:'tma '+initData(123)}})).status,200);
  assert.equal((await mf.dispatchFetch(`https://test/api/events/${galleryId}/media/${videoPreview.id}`,{headers:{Authorization:'tma '+initData(123)}})).status,413);
  // A one-use co-host link grants event management, but never ownership or payment control.
  const cohostInput={...input,date:'2099-10-24',title:'Co-host workflow',invitationMode:'named',guestNames:'Event guest = 2',askPhone:false,askComments:false,qrEnabled:true,requireApproval:true,hideLocation:true,ticketInfo:'PRIVATE CO-HOST TICKET',permissions:{guestList:false,uploadMedia:false,viewMedia:false},requestId:'99999999-9999-9999-9999-999999999999'};
  const cohostCreated=await api('events',cohostInput);assert.equal(cohostCreated.status,200);
  const cohostId=cohostCreated.data.event.id;
  assert.equal(cohostCreated.data.event.isOwner,true);assert.equal(cohostCreated.data.event.isManager,true);assert.equal(cohostCreated.data.event.isCoHost,false);assert.match(cohostCreated.data.event.cohostVersion,/^[a-f0-9]{16}$/);assert.deepEqual(cohostCreated.data.event.cohostLinks,[]);
  assert.equal((await api(`events/${cohostId}`,null,901)).status,403);
  const cohostInvited=await api(`events/${cohostId}/cohost/invite`,{version:cohostCreated.data.event.cohostVersion,label:'Door team'});assert.equal(cohostInvited.status,200);
  const cohostUrl=cohostInvited.data.event.cohostInviteUrl,pendingCohostVersion=cohostInvited.data.event.cohostVersion;
  const firstCohostLinkId=cohostInvited.data.event.cohostLinks[0].id;
  assert.equal(cohostInvited.data.event.cohostLinks[0].label,'Door team');assert.equal(cohostInvited.data.event.cohostLinks[0].status,'pending');assert.equal(cohostInvited.data.event.cohostLinks[0].token,undefined);
  assert.match(cohostUrl,/\?start=c_[a-f0-9]{16}_[a-f0-9]{32}$/);
  assert.equal((await api(`events/${cohostId}/cohost/invite`,{version:cohostCreated.data.event.cohostVersion,label:'Stale request'})).status,400);
  assert.equal((await api(`events/${cohostId}/cohost/invite`,{version:pendingCohostVersion,label:'x'.repeat(81)})).status,400);
  const secondCohostInvite=await api(`events/${cohostId}/cohost/invite`,{version:pendingCohostVersion,label:'Media team'});assert.equal(secondCohostInvite.status,200);
  const secondCohostEntry=secondCohostInvite.data.event.cohostLinks[1];assert.equal(secondCohostEntry.label,'Media team');assert.equal(secondCohostInvite.data.event.cohostLinks[0].url,cohostUrl);
  await message(8000,'/start '+new URL(cohostUrl).searchParams.get('start'),901);
  const cohostView=(await api(`events/${cohostId}`,null,901)).data.event;
  assert.equal(cohostView.isOwner,false);assert.equal(cohostView.isManager,true);assert.equal(cohostView.isCoHost,true);assert.equal(cohostView.cohost.id,901);
  assert.equal(cohostView.location,cohostInput.location);assert.equal(cohostView.ticketInfo,cohostInput.ticketInfo);assert.equal(cohostView.invitees.length,1);assert.ok(cohostView.guestRoster);
  assert.equal(cohostView.cohostInviteUrl,undefined);assert.equal(cohostView.cohostVersion,undefined);assert.equal(cohostView.cohostLinks,undefined);
  for(const link of [cohostUrl,secondCohostEntry.url])assert.equal(JSON.stringify(cohostView).includes(new URL(link).searchParams.get('start').split('_').at(-1)),false);
  assert.deepEqual(cohostView.cohosts.map(host=>host.id),[901]);
  assert.ok((await api('bootstrap',null,901)).data.events.some(e=>e.id===cohostId && e.isManager && !e.isOwner));
  await message(8001,'/start '+new URL(cohostUrl).searchParams.get('start'),904);
  assert.equal((await api(`events/${cohostId}`,null,904)).status,403);
  assert.equal((await api(`events/${cohostId}/cohost/revoke`,{version:pendingCohostVersion,linkId:firstCohostLinkId})).status,400);
  // An existing co-host cannot consume another person's invitation.
  await message(8020,'/start '+new URL(secondCohostEntry.url).searchParams.get('start'),901);
  assert.equal((await api(`events/${cohostId}`)).data.event.cohostLinks[1].status,'pending');
  await message(8021,'/start '+new URL(secondCohostEntry.url).searchParams.get('start'),903);
  const secondCohostView=(await api(`events/${cohostId}`,null,903)).data.event;assert.equal(secondCohostView.isManager,true);assert.deepEqual(secondCohostView.cohosts.map(host=>host.id),[901,903]);
  assert.ok((await api('bootstrap',null,903)).data.events.some(e=>e.id===cohostId && e.isCoHost));assert.equal(secondCohostView.location,cohostInput.location);
  // Cancelling one pending link preserves both claimed roles and the link history.
  const beforeThird=(await api(`events/${cohostId}`)).data.event;
  const thirdCohostInvite=await api(`events/${cohostId}/cohost/invite`,{version:beforeThird.cohostVersion,label:'Spare helper'});assert.equal(thirdCohostInvite.status,200);
  const thirdCohostEntry=thirdCohostInvite.data.event.cohostLinks[2];
  assert.equal((await api(`events/${cohostId}/cohost/revoke`,{version:thirdCohostInvite.data.event.cohostVersion})).status,400);
  const cancelledCohostLink=await api(`events/${cohostId}/cohost/revoke`,{version:thirdCohostInvite.data.event.cohostVersion,linkId:thirdCohostEntry.id});assert.equal(cancelledCohostLink.status,200);
  assert.deepEqual(cancelledCohostLink.data.event.cohosts.map(host=>host.id),[901,903]);assert.equal(cancelledCohostLink.data.event.cohostLinks[2].status,'revoked');assert.equal(cancelledCohostLink.data.event.cohostLinks[2].url,null);
  await message(8022,'/start '+new URL(thirdCohostEntry.url).searchParams.get('start'),904);assert.equal((await api(`events/${cohostId}`,null,904)).status,403);
  const cohostOwnerView=(await api(`events/${cohostId}`)).data.event;
  assert.equal(cohostOwnerView.cohost.id,901);assert.equal(cohostOwnerView.cohostInviteUrl,null);
  assert.equal((await api(`events/${cohostId}/cohost/invite`,{version:cohostOwnerView.cohostVersion},901)).status,400);
  assert.equal((await api(`events/${cohostId}/cohost/revoke`,{version:cohostOwnerView.cohostVersion,linkId:secondCohostEntry.id},901)).status,400);
  assert.equal(cohostOwnerView.cohostLinks[0].cohost.id,901);assert.equal(cohostOwnerView.cohostLinks[0].cohost.name,'Tester');assert.equal(cohostOwnerView.cohostLinks[0].cohost.username,'');
  assert.equal((await api(`events/${cohostId}/cancel`,{confirm:true},901)).status,400);
  assert.equal((await api(`events/${cohostId}/delete`,{confirm:true},901)).status,400);
  assert.equal((await api(`events/${cohostId}/schedule`,{...cohostInput,paymentMethod:'bank',displayPrice:'$20',paymentInstructions:'Transfer',paymentTerms:'No refunds'},901)).status,400);
  assert.equal((await api(`events/${cohostId}/schedule`,{...cohostInput,paymentTerms:'Changed terms'},901)).status,400);
  assert.equal((await api(`events/${cohostId}/schedule`,{...cohostInput,invitationMode:'tickets'},901)).status,400);
  const cohostEdited=await api(`events/${cohostId}/schedule`,{...cohostInput,title:'Updated by co-host',location:'Updated private venue',guestNames:'Event guest = 2\nAnother guest',permissions:{guestList:false,uploadMedia:true,viewMedia:false},paymentMethod:'free',starPrice:0,starPricing:'group',displayPrice:'',paymentInstructions:'',paymentUrl:'',paymentTerms:''},901);
  assert.equal(cohostEdited.status,200);assert.equal(cohostEdited.data.event.title,'Updated by co-host');assert.equal(cohostEdited.data.event.invitees.length,2);
  assert.equal((await api(`events/${cohostId}/schedule`,{...cohostInput,title:'Updated by second co-host',location:'Updated private venue',guestNames:'Event guest = 2\nAnother guest',permissions:{guestList:false,uploadMedia:true,viewMedia:false}},903)).status,200);
  const cohostStored=()=>db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(cohostId).first().then(row=>JSON.parse(row.data));
  assert.equal((await cohostStored()).owner,123);assert.equal((await cohostStored()).guests[901],undefined);
  const cohostBanner=await mf.dispatchFetch(`https://test/api/events/${cohostId}/banner`,{method:'POST',headers:{Authorization:'tma '+initData(901),'Content-Type':photoRequest.headers.get('Content-Type')},body:photoBytes});assert.equal(cohostBanner.status,200);
  assert.equal((await mf.dispatchFetch(`https://test/api/events/${cohostId}/banner`,{headers:{Authorization:'tma '+initData(901)}})).status,200);
  await callback(8002,`u:${cohostId}`,901);await message(8003,undefined,901,{photo:[{file_id:'cohost-photo',file_size:3}]});
  const cohostGallery=await api(`events/${cohostId}/gallery`,null,901);assert.equal(cohostGallery.status,200);assert.equal(cohostGallery.data.canUpload,true);assert.equal(cohostGallery.data.media.length,1);
  assert.equal((await api(`events/${cohostId}/upload-qr`,null,901)).status,200);
  const cohostMediaId=cohostGallery.data.media[0].id;
  assert.equal((await api(`events/${cohostId}/media/${cohostMediaId}/send`,{},901)).status,200);
  const eventGuestUrl=cohostCreated.data.event.invitees[0].url;
  await message(8004,'/start '+new URL(eventGuestUrl).searchParams.get('start'),902);await callback(8005,`r:${cohostId}:yes:0`,902);
  const cohostGuestView=(await api(`events/${cohostId}`,null,902)).data.event;
  assert.equal(cohostGuestView.location,'Updated private venue');assert.equal(cohostGuestView.cohost,undefined);assert.equal(cohostGuestView.guestRoster,undefined);assert.equal(cohostGuestView.cohostInviteUrl,undefined);assert.equal(cohostGuestView.cohostVersion,undefined);
  const cohostGuest=(await cohostStored()).guests[902];assert.equal(cohostGuest.approval,'approved');assert.ok(cohostGuest.ticket);
  const cohostCheckin=await api(`events/${cohostId}/ticket-check`,{code:cohostGuest.ticket,checkIn:true},901);assert.equal(cohostCheckin.status,200);assert.equal(cohostCheckin.data.ticket.valid,true);assert.equal(cohostCheckin.data.ticket.participants,2);
  assert.equal((await api(`events/${cohostId}/ticket-check`,{code:cohostGuest.ticket},903)).data.ticket.valid,true);
  await callback(8023,`u:${cohostId}`,903);
  const secondSession=await db.prepare("SELECT data FROM records WHERE kind='sessions' AND id='903'").first();assert.ok(secondSession);
  const beforeRevocationMessages=telegramCalls.length;
  const cohostRevoked=await api(`events/${cohostId}/cohost/revoke`,{version:cohostOwnerView.cohostVersion,linkId:firstCohostLinkId});assert.equal(cohostRevoked.status,200);assert.equal(cohostRevoked.data.event.cohost.id,903);assert.deepEqual(cohostRevoked.data.event.cohosts.map(host=>host.id),[903]);assert.equal(cohostRevoked.data.event.cohostLinks[0].status,'revoked');assert.equal(cohostRevoked.data.event.cohostLinks[0].cohost.id,901);
  assert.equal((await api(`events/${cohostId}/cohost/revoke`,{version:cohostOwnerView.cohostVersion,linkId:secondCohostEntry.id})).status,400);
  assert.equal((await api(`events/${cohostId}/gallery`,null,903)).status,200);assert.equal((await db.prepare("SELECT data FROM records WHERE kind='sessions' AND id='903'").first()).data,secondSession.data);
  assert.equal((await api(`events/${cohostId}`,null,901)).status,403);assert.ok(!(await api('bootstrap',null,901)).data.events.some(e=>e.id===cohostId));
  assert.equal((await api(`events/${cohostId}/schedule`,cohostInput,901)).status,400);
  assert.equal(await db.prepare("SELECT data FROM records WHERE kind='sessions' AND id='901'").first(),null);
  assert.equal((await api(`events/${cohostId}/gallery`,null,901)).status,403);
  assert.equal((await api(`events/${cohostId}/ticket-check`,{code:cohostGuest.ticket},901)).status,400);
  assert.equal((await mf.dispatchFetch(`https://test/api/events/${cohostId}/banner`,{headers:{Authorization:'tma '+initData(901)}})).status,403);
  const pendingNotifications=(await db.prepare("SELECT method,params FROM outbox WHERE method='sendMessage'").all()).results.map(row=>({method:row.method,params:JSON.parse(row.params)}));
  const removalMessages=[...telegramCalls.slice(beforeRevocationMessages),...pendingNotifications].filter(call=>call.method==='sendMessage' && call.params.text?.includes('co-host access') && call.params.text.includes('removed'));
  assert.ok(removalMessages.some(call=>call.params.chat_id===901));assert.equal(removalMessages.some(call=>call.params.chat_id===903),false);
  // Revocation restores normal guest rights without changing an existing booking or ticket.
  const guestCohostInvite=await api(`events/${cohostId}/cohost/invite`,{version:cohostRevoked.data.event.cohostVersion,label:'Guest helper'});assert.equal(guestCohostInvite.status,200);
  await message(8007,'/start '+new URL(guestCohostInvite.data.event.cohostInviteUrl).searchParams.get('start'),902);
  const retainedGuest=(await cohostStored()).guests[902];assert.equal(retainedGuest.ticket,cohostGuest.ticket);assert.equal(retainedGuest.participants,2);assert.equal(retainedGuest.status,'yes');
  assert.equal((await api(`events/${cohostId}/ticket`,{},902)).data.ticket.code,cohostGuest.ticket);
  assert.equal((await api(`events/${cohostId}`)).data.event.counts.participants,2);
  const guestCohostOwner=(await api(`events/${cohostId}`)).data.event;
  const guestCohostLinkId=guestCohostOwner.cohostLinks.find(entry=>entry.status==='active' && entry.cohost.id===902).id;
  assert.equal((await api(`events/${cohostId}/cohost/revoke`,{version:guestCohostOwner.cohostVersion,linkId:guestCohostLinkId})).status,200);
  const restoredGuest=(await api(`events/${cohostId}`,null,902)).data.event;
  assert.equal(restoredGuest.isManager,false);assert.equal(restoredGuest.isOwner,false);assert.equal(restoredGuest.ticket.code,cohostGuest.ticket);assert.equal(restoredGuest.participants,2);
  assert.equal((await api(`events/${cohostId}/gallery`,null,902)).status,403);
  const paidCohostInput={...cohostInput,title:'Paid co-host editing',invitationMode:'tickets',paymentMethod:'bank',displayPrice:'AUD $25',paymentInstructions:'Pay with your booking name as reference.',paymentTerms:'Contact the event owner about refunds.',requestId:'abababab-abab-abab-abab-abababababab'};
  const paidCohostCreated=await api('events',paidCohostInput);assert.equal(paidCohostCreated.status,200);
  const paidCohostId=paidCohostCreated.data.event.id;
  const paidCohostInvite=await api(`events/${paidCohostId}/cohost/invite`,{version:paidCohostCreated.data.event.cohostVersion,label:'Admissions'});
  await message(8008,'/start '+new URL(paidCohostInvite.data.event.cohostInviteUrl).searchParams.get('start'),905);
  const paidCohostView=(await api(`events/${paidCohostId}`,null,905)).data.event;
  assert.equal(paidCohostView.paymentInstructions,paidCohostInput.paymentInstructions);
  assert.equal((await api(`events/${paidCohostId}/schedule`,{...paidCohostInput,title:'Paid title updated by co-host'},905)).status,200);
  assert.equal((await api(`events/${paidCohostId}/schedule`,{...paidCohostInput,paymentInstructions:'A different bank account'},905)).status,400);
  assert.equal((await api(`events/${paidCohostId}/schedule`,{...paidCohostInput,displayPrice:'AUD $1'},905)).status,400);
  assert.equal(JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(paidCohostId).first()).data).owner,123);
  // Approval belongs to ticket booking; a co-host can approve a request but cannot bypass payment.
  await message(8010,`/start e_${paidCohostId}`,907);await callback(8011,`book:${paidCohostId}`,907);await message(8012,'Ticket guest',907);
  const pendingCohostTicket=(await api(`events/${paidCohostId}`,null,907)).data.event;
  assert.equal(pendingCohostTicket.approval,'pending');assert.equal(pendingCohostTicket.location,null);
  const paidCohostStored=JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(paidCohostId).first()).data);
  await callback(8013,`approve:${paidCohostId}:907:${paidCohostStored.guests[907].responseVersion}`,905);
  const approvedCohostTicket=(await api(`events/${paidCohostId}`,null,907)).data.event;
  assert.equal(approvedCohostTicket.approval,'approved');assert.equal(approvedCohostTicket.location,null);assert.equal(approvedCohostTicket.ticket,null);
  // Existing single-role JSON records remain readable and migrate only when changed.
  const legacyCohostCreated=await api('events',{...cohostInput,title:'Legacy co-host adapter',invitationMode:'tickets',requestId:'decafbad-1111-2222-3333-000000000001'});assert.equal(legacyCohostCreated.status,200);assert.equal(legacyCohostCreated.data.event.title,'Legacy co-host adapter');assert.equal(legacyCohostCreated.data.event.oneTimeInvite,false);
  const legacyCohostId=legacyCohostCreated.data.event.id;
  const legacyStored=JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(legacyCohostId).first()).data);
  legacyStored.cohost={id:1001,name:'Legacy host',username:'legacy_host',joinedAt:'2026-10-01T00:00:00Z'};
  legacyStored.cohostInvite={token:'c'.repeat(32),createdAt:'2026-10-02T00:00:00Z'};
  legacyStored.guests[1001]={name:'Existing guest booking',status:'yes',approval:'approved',participants:2,payment:{status:'paid',amount:50},ticket:'ABCDEF987654'};
  delete legacyStored.cohostLinks;
  await db.prepare("UPDATE records SET data=? WHERE kind='events' AND id=?").bind(JSON.stringify(legacyStored),legacyCohostId).run();
  assert.ok((await api('bootstrap',null,1001)).data.events.some(e=>e.id===legacyCohostId && e.isManager));
  const legacyOwner=(await api(`events/${legacyCohostId}`)).data.event;
  assert.equal(legacyOwner.cohostLinks.length,2);assert.equal(legacyOwner.cohostLinks[0].cohost.username,'legacy_host');assert.equal(legacyOwner.cohostLinks[1].status,'pending');
  assert.deepEqual(JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(legacyCohostId).first()).data),legacyStored);
  const legacyAdded=await api(`events/${legacyCohostId}/cohost/invite`,{version:legacyOwner.cohostVersion,label:'Additional helper'});assert.equal(legacyAdded.status,200);
  assert.equal(legacyAdded.data.event.cohostLinks[0].id,legacyOwner.cohostLinks[0].id);assert.equal(legacyAdded.data.event.cohostLinks[1].url,legacyOwner.cohostLinks[1].url);
  await message(8024,'/start '+new URL(legacyOwner.cohostLinks[1].url).searchParams.get('start'),1002);
  const legacyClaimed=(await api(`events/${legacyCohostId}`)).data.event;
  assert.equal(legacyClaimed.cohostLinks[1].id,legacyOwner.cohostLinks[1].id);assert.equal(legacyClaimed.cohostLinks[1].status,'active');assert.equal(legacyClaimed.cohostLinks[1].cohost.id,1002);
  assert.deepEqual(legacyClaimed.cohosts.map(host=>host.id),[1001,1002]);assert.ok((await api('bootstrap',null,1002)).data.events.some(e=>e.id===legacyCohostId && e.isManager));
  const legacyRevoked=await api(`events/${legacyCohostId}/cohost/revoke`,{version:legacyClaimed.cohostVersion,linkId:legacyOwner.cohostLinks[0].id});assert.equal(legacyRevoked.status,200);
  const legacyRestored=(await api(`events/${legacyCohostId}`,null,1001)).data.event;
  assert.equal(legacyRestored.isManager,false);assert.equal(legacyRestored.ticket.code,'ABCDEF987654');assert.equal((await api(`events/${legacyCohostId}`,null,1002)).data.event.isManager,true);
  const canonicalLegacy=JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(legacyCohostId).first()).data);
  assert.deepEqual(canonicalLegacy.guests,legacyStored.guests);
  // A stale compatibility alias cannot resurrect access or leak a reusable event via bootstrap.
  canonicalLegacy.cohost={id:1003,name:'Stale alias',username:'stale_alias',joinedAt:'2026-10-01T00:00:00Z'};
  await db.prepare("UPDATE records SET data=? WHERE kind='events' AND id=?").bind(JSON.stringify(canonicalLegacy),legacyCohostId).run();
  assert.equal((await api(`events/${legacyCohostId}`,null,1003)).status,403);assert.ok(!(await api('bootstrap',null,1003)).data.events.some(e=>e.id===legacyCohostId));
  // Legacy malformed visibility cannot publish a personal-invitation event or its banner.
  const malformedNamed=await cohostStored();malformedNamed.isPublic=true;malformedNamed.banner='test-banner';
  await db.prepare("UPDATE records SET data=? WHERE kind='events' AND id=?").bind(JSON.stringify(malformedNamed),cohostId).run();
  assert.ok(!(await api('explore?timezone=Australia%2FSydney',null,906)).data.events.some(e=>e.id===cohostId));
  assert.equal((await api(`events/${cohostId}`,null,906)).status,403);
  assert.equal((await mf.dispatchFetch(`https://test/api/events/${cohostId}/banner`,{headers:{Authorization:'tma '+initData(906)}})).status,403);
  assert.equal((await mf.dispatchFetch(`https://test/api/events/${cohostId}/banner`)).status,401);
  assert.equal((await mf.dispatchFetch(`https://test/api/events/${cohostId}/banner`,{headers:{Authorization:'tma '+initData(902)}})).status,200);
  // Native Telegram creation persists each short step in D1 without opening App.
  const nativeCreator=777123,nativeOutsider=777124;
  const nativeSession=async()=>{
    const row=await db.prepare("SELECT data FROM records WHERE kind='sessions' AND id=?").bind(String(nativeCreator)).first();
    return row?JSON.parse(row.data):null;
  };
  await message(80000,'/start',nativeCreator);
  assert.equal((await api('preferences',{timezone:'Australia/Sydney'},nativeCreator)).status,200);
  await message(80001,'🎉 Create event',nativeCreator);
  assert.equal((await nativeSession()).flow,'chat-create');
  await message(80002,'Native button meetup',nativeCreator);
  const nativeDateSession=await nativeSession();
  assert.equal(nativeDateSession.step,'chat-date');
  const nativeDateCallback=`cc:${nativeDateSession.token}:date:2099-11-25`;
  await callback(80003,nativeDateCallback,nativeCreator);
  const nativeTimeSession=await nativeSession();
  assert.equal(nativeTimeSession.step,'chat-time');
  assert.notEqual(nativeTimeSession.token,nativeDateSession.token);
  await callback(80004,nativeDateCallback,nativeOutsider);
  assert.deepEqual(await nativeSession(),nativeTimeSession);
  await callback(80005,nativeDateCallback,nativeCreator);
  assert.deepEqual(await nativeSession(),nativeTimeSession);
  await callback(80006,`cc:${nativeTimeSession.token}:time:1800`,nativeCreator);
  assert.equal((await nativeSession()).draft.startsAt,'2099-11-25T07:00:00Z');
  await message(80007,'Community park',nativeCreator);
  assert.equal((await nativeSession()).step,'chat-review');
  async function nativeAction(updateId,action,value){
    const current=await nativeSession();
    const data=`cc:${current.token}:${action}${value===undefined?'':':'+value}`;
    await callback(updateId,data,nativeCreator);return data;
  }
  await nativeAction(80008,'options');await nativeAction(80009,'reminders');await nativeAction(80010,'reminder',180);
  await nativeAction(80011,'review');
  const nativeCreateCallback=await nativeAction(80012,'create');
  assert.equal(await nativeSession(),null);
  const nativeEvents=(await api('bootstrap',null,nativeCreator)).data.events;
  assert.equal(nativeEvents.length,1);
  const nativeEvent=nativeEvents[0];
  assert.equal(nativeEvent.title,'Native button meetup');
  assert.equal(nativeEvent.startsAt,'2099-11-25T07:00:00Z');
  assert.equal(nativeEvent.timezone,'Australia/Sydney');
  assert.equal(nativeEvent.invitationMode,'tickets');
  assert.equal(nativeEvent.isPublic,false);
  assert.equal(nativeEvent.askPhone,false);
  assert.equal(nativeEvent.askComments,false);
  assert.equal(nativeEvent.qrEnabled,false);
  assert.equal(nativeEvent.requireApproval,false);
  assert.equal(nativeEvent.defaultReminder,180);
  assert.deepEqual(nativeEvent.permissions,{guestList:false,uploadMedia:false,viewMedia:false});
  assert.equal((await api(`events/${nativeEvent.id}`,null,nativeOutsider)).status,403);
  await callback(80013,nativeCreateCallback,nativeCreator);
  assert.equal((await api('bootstrap',null,nativeCreator)).data.events.length,1);
  const nativeCards=telegramCalls.filter(call=>call.params.chat_id===nativeCreator && call.params.reply_markup?.inline_keyboard?.flat().some(button=>button.callback_data?.startsWith('cc:')));
  assert.ok(nativeCards.length>=4);
  assert.ok(nativeCards.every(call=>call.params.reply_markup.inline_keyboard.flat().every(button=>!button.web_app)));
  // Native Location later remains editable through App and does not require a placeholder address.
  const nativeEditInput={date:'2099-11-25',time:'18:00',timezone:'Australia/Sydney'};
  const nativeWithoutAddress=await api(`events/${nativeEvent.id}/schedule`,{...nativeEditInput,location:''},nativeCreator);
  assert.equal(nativeWithoutAddress.status,200);assert.equal(nativeWithoutAddress.data.event.location,'');
  const nativeEditReuse=await api(`events/${nativeEvent.id}/schedule`,{...nativeEditInput,title:'Native event edited in App'},nativeCreator);
  assert.equal(nativeEditReuse.status,200);assert.equal(nativeEditReuse.data.event.location,'');
  assert.equal(nativeEditReuse.data.event.startsAt,nativeEvent.startsAt);
  const nativeAppCopy=await api('events',{...nativeEditInput,title:'App event with location later',description:'',invitationMode:'tickets',requestId:'77712300-0000-4000-8000-000000000001'},nativeCreator);
  assert.equal(nativeAppCopy.status,200,JSON.stringify(nativeAppCopy.data));assert.equal(nativeAppCopy.data.event.location,'');
  // Named invitation management retains links and responses when adding, and durably revokes removals.
  // Hold delivery briefly so notify/silent choices can be checked against exact durable outbox rows.
  const invitationDeliveryOwner='invitation-management-integration';
  let invitationDeliveryLock;
  for(let attempt=0;attempt<80 && !invitationDeliveryLock;attempt++){
    invitationDeliveryLock=await db.prepare('INSERT INTO delivery_lease(id,owner,expires) VALUES (1,?,unixepoch()+3600) ON CONFLICT(id) DO UPDATE SET owner=excluded.owner,expires=excluded.expires WHERE delivery_lease.expires<unixepoch() RETURNING owner').bind(invitationDeliveryOwner).first();
    if(!invitationDeliveryLock)await new Promise(resolve=>setTimeout(resolve,25));
  }
  assert.equal(invitationDeliveryLock?.owner,invitationDeliveryOwner);
  const invitationOwner=888123,invitationCohost=888124;
  const managementInput={title:'Invitation management',date:'2099-11-25',time:'18:00',timezone:'Australia/Sydney',location:'Club venue',description:'',invitationMode:'named',oneTimeInvite:false,askPhone:false,askComments:false,qrEnabled:true,defaultReminder:180,permissions:{guestList:false,uploadMedia:false,viewMedia:false},guestNames:'Accepted = 2\nMaybe = 3\nDeclined\nUnanswered = ?',requestId:'88812300-0000-4000-8000-000000000001'};
  const invitationCreated=await api('events',managementInput,invitationOwner);
  assert.equal(invitationCreated.status,200,JSON.stringify(invitationCreated.data));
  const invitationId=invitationCreated.data.event.id;
  const invitationPath=`events/${invitationId}/invitations`;
  const invitationStored=async()=>JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(invitationId).first()).data);
  const invitationSession=async uid=>{const row=await db.prepare("SELECT data FROM records WHERE kind='sessions' AND id=?").bind(String(uid)).first();return row?JSON.parse(row.data):null;};
  const invitationView=async (uid=invitationOwner)=>(await api(`events/${invitationId}`,null,uid)).data.event;
  const invitationOutbox=async()=>{const {results}=await db.prepare("SELECT id,method,params FROM outbox ORDER BY rowid").all();return results.map(row=>({...row,params:JSON.parse(row.params)}));};
  let invitationUpdate=90000;
  const managementInvite=name=>invitationCreated.data.event.invitees.find(guest=>guest.name===name);
  const openManagementInvite=async(name,uid)=>message(invitationUpdate++,'/start '+new URL(managementInvite(name).url).searchParams.get('start'),uid);
  const managementResponse=async(uid,status)=>{const guest=(await invitationStored()).guests[uid];await callback(invitationUpdate++,`r:${invitationId}:${status}:${guest?.responseVersion || 0}`,uid);};
  const managementCohost=await api(`events/${invitationId}/cohost/invite`,{version:invitationCreated.data.event.cohostVersion,label:'Guest coordinator'},invitationOwner);
  assert.equal(managementCohost.status,200);
  await message(invitationUpdate++,'/start '+new URL(managementCohost.data.event.cohostInviteUrl).searchParams.get('start'),invitationCohost);
  for(const uid of [888201,888202]){await openManagementInvite('Accepted',uid);await managementResponse(uid,'yes');}
  await openManagementInvite('Maybe',888203);await managementResponse(888203,'maybe');
  await openManagementInvite('Declined',888204);await managementResponse(888204,'no');
  await openManagementInvite('Accepted',888205);
  await callback(invitationUpdate++,`group:${invitationId}:edit:0`,888205);
  const removedCountPicker=await invitationSession(888205);
  assert.equal(removedCountPicker.step,'participants');
  let managedView=await invitationView();
  const acceptedInvite=managedView.invitees.find(guest=>guest.name==='Accepted');
  assert.match(managedView.invitationsVersion,/^[a-f0-9]{16}$/);
  assert.equal(acceptedInvite.status,'mixed');
  assert.deepEqual(acceptedInvite.responseCounts,{yes:2,no:0,maybe:0,later:1});
  assert.deepEqual(acceptedInvite.responses.map(response=>response.id).sort(),[888201,888202,888205]);
  assert.equal(managedView.invitees.find(guest=>guest.name==='Maybe').status,'maybe');
  assert.equal(managedView.invitees.find(guest=>guest.name==='Declined').status,'no');
  assert.equal(managedView.invitees.find(guest=>guest.name==='Unanswered').status,null);
  assert.equal(managedView.counts.participants,4);
  assert.equal((await invitationView(invitationCohost)).invitationsVersion,managedView.invitationsVersion);
  const guestManagementView=(await api(`events/${invitationId}`,null,888201)).data.event;
  assert.equal(guestManagementView.invitees,undefined);assert.equal(guestManagementView.invitationsVersion,undefined);
  const originalInvitations=(await invitationStored()).invitees;
  const addition={guestNames:'New guest = 2!\nLast guest = ?',requestId:'88812300-0000-4000-8000-000000000002',version:managedView.invitationsVersion};
  assert.equal((await api(invitationPath+'/add',addition,888201)).status,400);
  assert.equal((await api(invitationPath+'/add',{...addition,version:'0'.repeat(16)},invitationOwner)).status,400);
  assert.equal((await api(invitationPath+'/add',{...addition,guestNames:'Accepted'},invitationOwner)).status,400);
  assert.deepEqual((await invitationStored()).invitees,originalInvitations);
  const invitationAdded=await api(invitationPath+'/add',addition,invitationCohost);
  assert.equal(invitationAdded.status,200,JSON.stringify(invitationAdded.data));assert.equal(invitationAdded.data.added,2);
  assert.equal(invitationAdded.data.event.invitees.length,6);
  for(const [token,invite] of Object.entries(originalInvitations))assert.deepEqual((await invitationStored()).invitees[token],invite);
  const staleInvitationEdit=await api(`events/${invitationId}/schedule`,{date:managementInput.date,time:managementInput.time,timezone:managementInput.timezone,guestNames:managementInput.guestNames,invitationsVersion:managedView.invitationsVersion},invitationOwner);
  assert.equal(staleInvitationEdit.status,400);assert.equal((await invitationView()).invitees.length,6);
  const additionReplay=await api(invitationPath+'/add',addition,invitationCohost);
  assert.equal(additionReplay.status,200);assert.equal(additionReplay.data.added,0);assert.equal(additionReplay.data.alreadyAdded,true);
  assert.equal((await invitationView()).invitees.length,6);
  managedView=await invitationView();
  const silentRemoval={token:acceptedInvite.token,notify:false,confirm:true,version:managedView.invitationsVersion};
  assert.equal((await api(invitationPath+'/remove',silentRemoval,888201)).status,400);
  assert.equal((await api(invitationPath+'/remove',{...silentRemoval,confirm:false},invitationOwner)).status,400);
  assert.equal((await api(invitationPath+'/remove',{...silentRemoval,notify:'false'},invitationOwner)).status,400);
  assert.equal((await api(invitationPath+'/remove',{...silentRemoval,version:'0'.repeat(16)},invitationOwner)).status,400);
  assert.equal((await api(invitationPath+'/remove',{...silentRemoval,token:'f'.repeat(32)},invitationOwner)).status,400);
  const beforeSilentRows=await invitationOutbox(),beforeSilentIds=new Set(beforeSilentRows.map(row=>row.id));
  const acceptedBeforeRemoval=await invitationStored();
  assert.ok(acceptedBeforeRemoval.reminders[888201]);assert.ok(acceptedBeforeRemoval.reminders[888202]);
  const removedTickets=[acceptedBeforeRemoval.guests[888201].ticket,acceptedBeforeRemoval.guests[888202].ticket];
  const unrelatedInvitationSession={step:'upload',event:nativeEvent.id};
  await db.prepare("INSERT INTO records(kind,id,data) VALUES ('sessions','888202',?) ON CONFLICT(kind,id) DO UPDATE SET data=excluded.data").bind(JSON.stringify(unrelatedInvitationSession)).run();
  const silentlyRemoved=await api(invitationPath+'/remove',silentRemoval,invitationCohost);
  assert.equal(silentlyRemoved.status,200,JSON.stringify(silentlyRemoved.data));assert.equal(silentlyRemoved.data.removed,true);assert.equal(silentlyRemoved.data.notifyCount,0);
  const silentlyRemovedState=await invitationStored();
  assert.equal(silentlyRemovedState.invitees[acceptedInvite.token],undefined);
  for(const uid of [888201,888202,888205]){
    assert.equal(silentlyRemovedState.guests[uid],undefined);assert.equal(silentlyRemovedState.reminders[uid],undefined);
    assert.deepEqual(await invitationSession(uid),uid===888202?unrelatedInvitationSession:null);
    assert.equal((await api(`events/${invitationId}`,null,uid)).status,403);
    assert.ok(!(await api('bootstrap',null,uid)).data.events.some(event=>event.id===invitationId));
  }
  assert.equal(silentlyRemoved.data.event.counts.yes,0);assert.equal(silentlyRemoved.data.event.counts.participants,0);
  assert.equal((await invitationOutbox()).filter(row=>!beforeSilentIds.has(row.id) && [888201,888202,888205].includes(row.params.chat_id)).length,0);
  for(const code of removedTickets)assert.equal((await api(`events/${invitationId}/ticket-check`,{code},invitationCohost)).data.ticket.valid,false);
  const silentReplay=await api(invitationPath+'/remove',silentRemoval,invitationCohost);
  assert.equal(silentReplay.status,200);assert.equal(silentReplay.data.alreadyRemoved,true);assert.equal(silentReplay.data.notifyCount,0);
  await openManagementInvite('Accepted',888201);await callback(invitationUpdate++,`r:${invitationId}:yes:1`,888201);
  assert.equal((await invitationStored()).guests[888201],undefined);
  assert.equal((await api(`events/${invitationId}`,null,888201)).status,403);
  await callback(invitationUpdate++,`size:${invitationId}:4:${removedCountPicker.countToken}`,888205);
  assert.equal((await invitationStored()).guests[888205],undefined);assert.equal(await invitationSession(888205),null);
  // Notify reaches only accounts which opened this personal link; retries never enqueue it twice.
  managedView=await invitationView();
  const maybeInvite=managedView.invitees.find(guest=>guest.name==='Maybe');
  const notificationRemoval={token:maybeInvite.token,notify:true,confirm:true,version:managedView.invitationsVersion};
  const beforeNotifyIds=new Set((await invitationOutbox()).map(row=>row.id));
  const notifiedRemoval=await api(invitationPath+'/remove',notificationRemoval,invitationOwner);
  assert.equal(notifiedRemoval.status,200);assert.equal(notifiedRemoval.data.notifyCount,1);
  const notifiedRows=(await invitationOutbox()).filter(row=>!beforeNotifyIds.has(row.id));
  assert.equal(notifiedRows.filter(row=>row.method==='sendMessage' && row.params.chat_id===888203).length,1);
  assert.equal(notifiedRows.filter(row=>row.method==='sendMessage' && [888201,888202,888204,888205].includes(row.params.chat_id)).length,0);
  const notificationReplay=await api(invitationPath+'/remove',notificationRemoval,invitationOwner);
  assert.equal(notificationReplay.status,200);assert.equal(notificationReplay.data.notifyCount,0);assert.equal(notificationReplay.data.alreadyRemoved,true);
  assert.equal((await invitationOutbox()).filter(row=>!beforeNotifyIds.has(row.id) && row.method==='sendMessage' && row.params.chat_id===888203).length,1);
  managedView=await invitationView();
  const unopenedInvite=managedView.invitees.find(guest=>guest.name==='Unanswered');
  assert.equal((await api(invitationPath+'/remove',{token:unopenedInvite.token,notify:true,confirm:true,version:managedView.invitationsVersion},invitationOwner)).data.notifyCount,0);
  // Expired response deadlines do not prevent maintenance, but cancelled events and other modes do.
  await db.prepare("UPDATE records SET data=json_set(data,'$.responseDeadline','2020-01-01T00:00:00Z') WHERE kind='events' AND id=?").bind(invitationId).run();
  managedView=await invitationView();
  assert.equal((await api(invitationPath+'/add',{guestNames:'After deadline',requestId:'88812300-0000-4000-8000-000000000003',version:managedView.invitationsVersion},invitationOwner)).status,200);
  const ticketManagement=await api('events',{...managementInput,invitationMode:'tickets',requestId:'88812300-0000-4000-8000-000000000004'},invitationOwner);
  assert.equal(ticketManagement.status,200);
  assert.equal((await api(`events/${ticketManagement.data.event.id}/invitations/add`,{...addition,version:ticketManagement.data.event.invitationsVersion},invitationOwner)).status,400);
  const pastManagement=await api('events',{...managementInput,title:'Finished invitation management',date:'2020-11-25',requestId:'88812300-0000-4000-8000-000000000006'},invitationOwner);
  assert.equal(pastManagement.status,200);
  assert.equal((await api(`events/${pastManagement.data.event.id}/invitations/add`,{...addition,version:pastManagement.data.event.invitationsVersion},invitationOwner)).status,400);
  assert.equal((await api(`events/${pastManagement.data.event.id}/invitations/remove`,{token:pastManagement.data.event.invitees[0].token,notify:false,confirm:true,version:pastManagement.data.event.invitationsVersion},invitationOwner)).status,400);
  assert.equal((await api(`events/${invitationId}/cancel`,{confirm:true},invitationOwner)).status,200);
  managedView=await invitationView();
  assert.equal((await api(invitationPath+'/add',{...addition,requestId:'88812300-0000-4000-8000-000000000005',version:managedView.invitationsVersion},invitationOwner)).status,400);
  assert.equal((await api(invitationPath+'/remove',{token:managedView.invitees[0].token,notify:false,confirm:true,version:managedView.invitationsVersion},invitationOwner)).status,400);
  // Fixed named counts survive create/edit/add; guests cannot use stale or forged count controls.
  const fixedOwner=890123,fixedGuestId=890201,flexibleGuestId=890202;
  const fixedInput={...managementInput,title:'Fixed attendee invitations',guestNames:'Fixed Guest = 2*\nFlexible Guest = 2',requestId:'89012300-0000-4000-8000-000000000001'};
  const fixedCreated=await api('events',fixedInput,fixedOwner);
  assert.equal(fixedCreated.status,200,JSON.stringify(fixedCreated.data));
  const fixedId=fixedCreated.data.event.id,fixedPath=`events/${fixedId}`;
  const fixedInvite=fixedCreated.data.event.invitees.find(guest=>guest.name==='Fixed Guest');
  assert.equal(fixedInvite.participantMode,'fixed');assert.equal(fixedInvite.participants,2);
  const fixedEdited=await api(fixedPath+'/schedule',{...fixedInput,title:'Edited fixed attendee invitations',invitationsVersion:fixedCreated.data.event.invitationsVersion},fixedOwner);
  assert.equal(fixedEdited.status,200,JSON.stringify(fixedEdited.data));
  assert.equal(fixedEdited.data.event.invitees.find(guest=>guest.name==='Fixed Guest').url,fixedInvite.url);
  assert.equal(fixedEdited.data.event.invitees.find(guest=>guest.name==='Fixed Guest').participantMode,'fixed');
  const fixedAdded=await api(fixedPath+'/invitations/add',{guestNames:'Added Fixed Guest = 3*',requestId:'89012300-0000-4000-8000-000000000002',version:fixedEdited.data.event.invitationsVersion},fixedOwner);
  assert.equal(fixedAdded.status,200,JSON.stringify(fixedAdded.data));
  const addedFixedInvite=fixedAdded.data.event.invitees.find(guest=>guest.name==='Added Fixed Guest');
  assert.equal(addedFixedInvite.participantMode,'fixed');assert.equal(addedFixedInvite.participants,3);
  assert.equal(fixedAdded.data.event.invitees.find(guest=>guest.name==='Fixed Guest').url,fixedInvite.url);
  const fixedRecord=async()=>JSON.parse((await db.prepare("SELECT data FROM records WHERE kind='events' AND id=?").bind(fixedId).first()).data);
  let fixedUpdate=95000;
  const openFixedInvite=async(invite,uid)=>message(fixedUpdate++,'/start '+new URL(invite.url).searchParams.get('start'),uid);
  const fixedCards=async uid=>(await invitationOutbox()).filter(row=>row.method==='sendMessage' && row.params.chat_id===uid && row.params.reply_markup?.inline_keyboard?.flat().some(button=>button.callback_data?.includes(':'+fixedId)));
  const countButtons=card=>card.params.reply_markup.inline_keyboard.flat().filter(button=>button.callback_data?.startsWith(`group:${fixedId}:`));
  await openFixedInvite(fixedInvite,fixedGuestId);
  let fixedCard=(await fixedCards(fixedGuestId)).at(-1);
  assert.equal(countButtons(fixedCard).length,0);
  const countEntity=fixedCard.params.entities.find(entity=>entity.type==='bold');
  assert.ok(countEntity);assert.match(fixedCard.params.text.slice(countEntity.offset,countEntity.offset+countEntity.length),/^2 (?:people|places)$/);
  await callback(fixedUpdate++,`group:${fixedId}:edit:0`,fixedGuestId);
  assert.equal(await countSession(fixedGuestId),null);
  await callback(fixedUpdate++,`r:${fixedId}:yes:0`,fixedGuestId);
  let fixedGuest=(await fixedRecord()).guests[fixedGuestId];
  assert.equal(fixedGuest.status,'yes');assert.equal(fixedGuest.participants,2);assert.equal(await countSession(fixedGuestId),null);
  assert.equal((await api(fixedPath,null,fixedGuestId)).data.event.participants,2);
  const fixedTicket=fixedGuest.ticket;
  await callback(fixedUpdate++,`group:${fixedId}:edit:${fixedGuest.responseVersion}`,fixedGuestId);
  await callback(fixedUpdate++,`size:${fixedId}:9:forged-token`,fixedGuestId);
  fixedGuest=(await fixedRecord()).guests[fixedGuestId];
  assert.equal(fixedGuest.participants,2);assert.equal(fixedGuest.ticket,fixedTicket);assert.equal(await countSession(fixedGuestId),null);
  fixedCard=(await fixedCards(fixedGuestId)).at(-1);assert.equal(countButtons(fixedCard).length,0);
  // Editable presets show their actual selected size on the button, including after acceptance.
  const flexibleInvite=fixedCreated.data.event.invitees.find(guest=>guest.name==='Flexible Guest');
  await openFixedInvite(flexibleInvite,flexibleGuestId);
  assert.match(countButtons((await fixedCards(flexibleGuestId)).at(-1))[0].text,/^2 people/);
  await callback(fixedUpdate++,`group:${fixedId}:edit:0`,flexibleGuestId);
  const flexiblePicker=await countSession(flexibleGuestId);assert.equal(flexiblePicker.step,'participants');
  await callback(fixedUpdate++,`size:${fixedId}:3:${flexiblePicker.countToken}`,flexibleGuestId);
  assert.equal((await fixedRecord()).guests[flexibleGuestId].participants,3);
  assert.match(countButtons((await fixedCards(flexibleGuestId)).at(-1))[0].text,/^3 people/);
  await callback(fixedUpdate++,`r:${fixedId}:yes:${(await fixedRecord()).guests[flexibleGuestId].responseVersion}`,flexibleGuestId);
  assert.match(countButtons((await fixedCards(flexibleGuestId)).at(-1))[0].text,/^3 people/);
  assert.equal((await api(fixedPath,null,flexibleGuestId)).data.event.participants,3);
  assert.equal((await api(fixedPath,null,fixedOwner)).data.event.counts.participants,5);
  await db.prepare('DELETE FROM delivery_lease WHERE owner=?').bind(invitationDeliveryOwner).run();
  console.log('Worker integration passed: fixed personal attendee counts and live count button captions, invitation response summaries, add/revoke with notify or silent removal, exact durable notifications, native button event creation, profiles, private photos, ticket bookings, personal RSVP links, multiple tagged co-host links and isolated revocation, legacy co-host migration, approvals, payments, durable refunds and media. Telegram mocked.');
} finally { await mf.dispose(); }
